// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/usagecardplan"
	"github.com/Wei-Shaw/sub2api/ent/userusagecard"
)

// UsageCardPlanCreate is the builder for creating a UsageCardPlan entity.
type UsageCardPlanCreate struct {
	config
	mutation *UsageCardPlanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *UsageCardPlanCreate) SetName(v string) *UsageCardPlanCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *UsageCardPlanCreate) SetDescription(v string) *UsageCardPlanCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *UsageCardPlanCreate) SetNillableDescription(v *string) *UsageCardPlanCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetProductName sets the "product_name" field.
func (_c *UsageCardPlanCreate) SetProductName(v string) *UsageCardPlanCreate {
	_c.mutation.SetProductName(v)
	return _c
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_c *UsageCardPlanCreate) SetNillableProductName(v *string) *UsageCardPlanCreate {
	if v != nil {
		_c.SetProductName(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *UsageCardPlanCreate) SetPrice(v float64) *UsageCardPlanCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetAmountUsd sets the "amount_usd" field.
func (_c *UsageCardPlanCreate) SetAmountUsd(v float64) *UsageCardPlanCreate {
	_c.mutation.SetAmountUsd(v)
	return _c
}

// SetValidityDays sets the "validity_days" field.
func (_c *UsageCardPlanCreate) SetValidityDays(v int) *UsageCardPlanCreate {
	_c.mutation.SetValidityDays(v)
	return _c
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_c *UsageCardPlanCreate) SetNillableValidityDays(v *int) *UsageCardPlanCreate {
	if v != nil {
		_c.SetValidityDays(*v)
	}
	return _c
}

// SetFeatures sets the "features" field.
func (_c *UsageCardPlanCreate) SetFeatures(v string) *UsageCardPlanCreate {
	_c.mutation.SetFeatures(v)
	return _c
}

// SetNillableFeatures sets the "features" field if the given value is not nil.
func (_c *UsageCardPlanCreate) SetNillableFeatures(v *string) *UsageCardPlanCreate {
	if v != nil {
		_c.SetFeatures(*v)
	}
	return _c
}

// SetForSale sets the "for_sale" field.
func (_c *UsageCardPlanCreate) SetForSale(v bool) *UsageCardPlanCreate {
	_c.mutation.SetForSale(v)
	return _c
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_c *UsageCardPlanCreate) SetNillableForSale(v *bool) *UsageCardPlanCreate {
	if v != nil {
		_c.SetForSale(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *UsageCardPlanCreate) SetSortOrder(v int) *UsageCardPlanCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *UsageCardPlanCreate) SetNillableSortOrder(v *int) *UsageCardPlanCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UsageCardPlanCreate) SetCreatedAt(v time.Time) *UsageCardPlanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UsageCardPlanCreate) SetNillableCreatedAt(v *time.Time) *UsageCardPlanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UsageCardPlanCreate) SetUpdatedAt(v time.Time) *UsageCardPlanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UsageCardPlanCreate) SetNillableUpdatedAt(v *time.Time) *UsageCardPlanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddUsageCardIDs adds the "usage_cards" edge to the UserUsageCard entity by IDs.
func (_c *UsageCardPlanCreate) AddUsageCardIDs(ids ...int64) *UsageCardPlanCreate {
	_c.mutation.AddUsageCardIDs(ids...)
	return _c
}

// AddUsageCards adds the "usage_cards" edges to the UserUsageCard entity.
func (_c *UsageCardPlanCreate) AddUsageCards(v ...*UserUsageCard) *UsageCardPlanCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageCardIDs(ids...)
}

// AddRedeemCodeIDs adds the "redeem_codes" edge to the RedeemCode entity by IDs.
func (_c *UsageCardPlanCreate) AddRedeemCodeIDs(ids ...int64) *UsageCardPlanCreate {
	_c.mutation.AddRedeemCodeIDs(ids...)
	return _c
}

// AddRedeemCodes adds the "redeem_codes" edges to the RedeemCode entity.
func (_c *UsageCardPlanCreate) AddRedeemCodes(v ...*RedeemCode) *UsageCardPlanCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRedeemCodeIDs(ids...)
}

// Mutation returns the UsageCardPlanMutation object of the builder.
func (_c *UsageCardPlanCreate) Mutation() *UsageCardPlanMutation {
	return _c.mutation
}

// Save creates the UsageCardPlan in the database.
func (_c *UsageCardPlanCreate) Save(ctx context.Context) (*UsageCardPlan, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsageCardPlanCreate) SaveX(ctx context.Context) *UsageCardPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageCardPlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageCardPlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UsageCardPlanCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := usagecardplan.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.ProductName(); !ok {
		v := usagecardplan.DefaultProductName
		_c.mutation.SetProductName(v)
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		v := usagecardplan.DefaultValidityDays
		_c.mutation.SetValidityDays(v)
	}
	if _, ok := _c.mutation.Features(); !ok {
		v := usagecardplan.DefaultFeatures
		_c.mutation.SetFeatures(v)
	}
	if _, ok := _c.mutation.ForSale(); !ok {
		v := usagecardplan.DefaultForSale
		_c.mutation.SetForSale(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := usagecardplan.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usagecardplan.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usagecardplan.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsageCardPlanCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UsageCardPlan.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := usagecardplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UsageCardPlan.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "UsageCardPlan.description"`)}
	}
	if _, ok := _c.mutation.ProductName(); !ok {
		return &ValidationError{Name: "product_name", err: errors.New(`ent: missing required field "UsageCardPlan.product_name"`)}
	}
	if v, ok := _c.mutation.ProductName(); ok {
		if err := usagecardplan.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "UsageCardPlan.product_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "UsageCardPlan.price"`)}
	}
	if _, ok := _c.mutation.AmountUsd(); !ok {
		return &ValidationError{Name: "amount_usd", err: errors.New(`ent: missing required field "UsageCardPlan.amount_usd"`)}
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		return &ValidationError{Name: "validity_days", err: errors.New(`ent: missing required field "UsageCardPlan.validity_days"`)}
	}
	if _, ok := _c.mutation.Features(); !ok {
		return &ValidationError{Name: "features", err: errors.New(`ent: missing required field "UsageCardPlan.features"`)}
	}
	if _, ok := _c.mutation.ForSale(); !ok {
		return &ValidationError{Name: "for_sale", err: errors.New(`ent: missing required field "UsageCardPlan.for_sale"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "UsageCardPlan.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageCardPlan.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UsageCardPlan.updated_at"`)}
	}
	return nil
}

func (_c *UsageCardPlanCreate) sqlSave(ctx context.Context) (*UsageCardPlan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsageCardPlanCreate) createSpec() (*UsageCardPlan, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageCardPlan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usagecardplan.Table, sqlgraph.NewFieldSpec(usagecardplan.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(usagecardplan.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(usagecardplan.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.ProductName(); ok {
		_spec.SetField(usagecardplan.FieldProductName, field.TypeString, value)
		_node.ProductName = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(usagecardplan.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.AmountUsd(); ok {
		_spec.SetField(usagecardplan.FieldAmountUsd, field.TypeFloat64, value)
		_node.AmountUsd = value
	}
	if value, ok := _c.mutation.ValidityDays(); ok {
		_spec.SetField(usagecardplan.FieldValidityDays, field.TypeInt, value)
		_node.ValidityDays = value
	}
	if value, ok := _c.mutation.Features(); ok {
		_spec.SetField(usagecardplan.FieldFeatures, field.TypeString, value)
		_node.Features = value
	}
	if value, ok := _c.mutation.ForSale(); ok {
		_spec.SetField(usagecardplan.FieldForSale, field.TypeBool, value)
		_node.ForSale = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(usagecardplan.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usagecardplan.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usagecardplan.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UsageCardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagecardplan.UsageCardsTable,
			Columns: []string{usagecardplan.UsageCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userusagecard.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RedeemCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagecardplan.RedeemCodesTable,
			Columns: []string{usagecardplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageCardPlan.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageCardPlanUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageCardPlanCreate) OnConflict(opts ...sql.ConflictOption) *UsageCardPlanUpsertOne {
	_c.conflict = opts
	return &UsageCardPlanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageCardPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageCardPlanCreate) OnConflictColumns(columns ...string) *UsageCardPlanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageCardPlanUpsertOne{
		create: _c,
	}
}

type (
	// UsageCardPlanUpsertOne is the builder for "upsert"-ing
	//  one UsageCardPlan node.
	UsageCardPlanUpsertOne struct {
		create *UsageCardPlanCreate
	}

	// UsageCardPlanUpsert is the "OnConflict" setter.
	UsageCardPlanUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *UsageCardPlanUpsert) SetName(v string) *UsageCardPlanUpsert {
	u.Set(usagecardplan.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UsageCardPlanUpsert) UpdateName() *UsageCardPlanUpsert {
	u.SetExcluded(usagecardplan.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *UsageCardPlanUpsert) SetDescription(v string) *UsageCardPlanUpsert {
	u.Set(usagecardplan.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *UsageCardPlanUpsert) UpdateDescription() *UsageCardPlanUpsert {
	u.SetExcluded(usagecardplan.FieldDescription)
	return u
}

// SetProductName sets the "product_name" field.
func (u *UsageCardPlanUpsert) SetProductName(v string) *UsageCardPlanUpsert {
	u.Set(usagecardplan.FieldProductName, v)
	return u
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *UsageCardPlanUpsert) UpdateProductName() *UsageCardPlanUpsert {
	u.SetExcluded(usagecardplan.FieldProductName)
	return u
}

// SetPrice sets the "price" field.
func (u *UsageCardPlanUpsert) SetPrice(v float64) *UsageCardPlanUpsert {
	u.Set(usagecardplan.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *UsageCardPlanUpsert) UpdatePrice() *UsageCardPlanUpsert {
	u.SetExcluded(usagecardplan.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *UsageCardPlanUpsert) AddPrice(v float64) *UsageCardPlanUpsert {
	u.Add(usagecardplan.FieldPrice, v)
	return u
}

// SetAmountUsd sets the "amount_usd" field.
func (u *UsageCardPlanUpsert) SetAmountUsd(v float64) *UsageCardPlanUpsert {
	u.Set(usagecardplan.FieldAmountUsd, v)
	return u
}

// UpdateAmountUsd sets the "amount_usd" field to the value that was provided on create.
func (u *UsageCardPlanUpsert) UpdateAmountUsd() *UsageCardPlanUpsert {
	u.SetExcluded(usagecardplan.FieldAmountUsd)
	return u
}

// AddAmountUsd adds v to the "amount_usd" field.
func (u *UsageCardPlanUpsert) AddAmountUsd(v float64) *UsageCardPlanUpsert {
	u.Add(usagecardplan.FieldAmountUsd, v)
	return u
}

// SetValidityDays sets the "validity_days" field.
func (u *UsageCardPlanUpsert) SetValidityDays(v int) *UsageCardPlanUpsert {
	u.Set(usagecardplan.FieldValidityDays, v)
	return u
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *UsageCardPlanUpsert) UpdateValidityDays() *UsageCardPlanUpsert {
	u.SetExcluded(usagecardplan.FieldValidityDays)
	return u
}

// AddValidityDays adds v to the "validity_days" field.
func (u *UsageCardPlanUpsert) AddValidityDays(v int) *UsageCardPlanUpsert {
	u.Add(usagecardplan.FieldValidityDays, v)
	return u
}

// SetFeatures sets the "features" field.
func (u *UsageCardPlanUpsert) SetFeatures(v string) *UsageCardPlanUpsert {
	u.Set(usagecardplan.FieldFeatures, v)
	return u
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *UsageCardPlanUpsert) UpdateFeatures() *UsageCardPlanUpsert {
	u.SetExcluded(usagecardplan.FieldFeatures)
	return u
}

// SetForSale sets the "for_sale" field.
func (u *UsageCardPlanUpsert) SetForSale(v bool) *UsageCardPlanUpsert {
	u.Set(usagecardplan.FieldForSale, v)
	return u
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *UsageCardPlanUpsert) UpdateForSale() *UsageCardPlanUpsert {
	u.SetExcluded(usagecardplan.FieldForSale)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *UsageCardPlanUpsert) SetSortOrder(v int) *UsageCardPlanUpsert {
	u.Set(usagecardplan.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *UsageCardPlanUpsert) UpdateSortOrder() *UsageCardPlanUpsert {
	u.SetExcluded(usagecardplan.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *UsageCardPlanUpsert) AddSortOrder(v int) *UsageCardPlanUpsert {
	u.Add(usagecardplan.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UsageCardPlanUpsert) SetUpdatedAt(v time.Time) *UsageCardPlanUpsert {
	u.Set(usagecardplan.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UsageCardPlanUpsert) UpdateUpdatedAt() *UsageCardPlanUpsert {
	u.SetExcluded(usagecardplan.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UsageCardPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageCardPlanUpsertOne) UpdateNewValues() *UsageCardPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usagecardplan.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageCardPlan.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UsageCardPlanUpsertOne) Ignore() *UsageCardPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageCardPlanUpsertOne) DoNothing() *UsageCardPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageCardPlanCreate.OnConflict
// documentation for more info.
func (u *UsageCardPlanUpsertOne) Update(set func(*UsageCardPlanUpsert)) *UsageCardPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageCardPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *UsageCardPlanUpsertOne) SetName(v string) *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UsageCardPlanUpsertOne) UpdateName() *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *UsageCardPlanUpsertOne) SetDescription(v string) *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *UsageCardPlanUpsertOne) UpdateDescription() *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateDescription()
	})
}

// SetProductName sets the "product_name" field.
func (u *UsageCardPlanUpsertOne) SetProductName(v string) *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetProductName(v)
	})
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *UsageCardPlanUpsertOne) UpdateProductName() *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateProductName()
	})
}

// SetPrice sets the "price" field.
func (u *UsageCardPlanUpsertOne) SetPrice(v float64) *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *UsageCardPlanUpsertOne) AddPrice(v float64) *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *UsageCardPlanUpsertOne) UpdatePrice() *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdatePrice()
	})
}

// SetAmountUsd sets the "amount_usd" field.
func (u *UsageCardPlanUpsertOne) SetAmountUsd(v float64) *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetAmountUsd(v)
	})
}

// AddAmountUsd adds v to the "amount_usd" field.
func (u *UsageCardPlanUpsertOne) AddAmountUsd(v float64) *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.AddAmountUsd(v)
	})
}

// UpdateAmountUsd sets the "amount_usd" field to the value that was provided on create.
func (u *UsageCardPlanUpsertOne) UpdateAmountUsd() *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateAmountUsd()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *UsageCardPlanUpsertOne) SetValidityDays(v int) *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *UsageCardPlanUpsertOne) AddValidityDays(v int) *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *UsageCardPlanUpsertOne) UpdateValidityDays() *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateValidityDays()
	})
}

// SetFeatures sets the "features" field.
func (u *UsageCardPlanUpsertOne) SetFeatures(v string) *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetFeatures(v)
	})
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *UsageCardPlanUpsertOne) UpdateFeatures() *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateFeatures()
	})
}

// SetForSale sets the "for_sale" field.
func (u *UsageCardPlanUpsertOne) SetForSale(v bool) *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetForSale(v)
	})
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *UsageCardPlanUpsertOne) UpdateForSale() *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateForSale()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *UsageCardPlanUpsertOne) SetSortOrder(v int) *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *UsageCardPlanUpsertOne) AddSortOrder(v int) *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *UsageCardPlanUpsertOne) UpdateSortOrder() *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UsageCardPlanUpsertOne) SetUpdatedAt(v time.Time) *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UsageCardPlanUpsertOne) UpdateUpdatedAt() *UsageCardPlanUpsertOne {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UsageCardPlanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageCardPlanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageCardPlanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UsageCardPlanUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UsageCardPlanUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UsageCardPlanCreateBulk is the builder for creating many UsageCardPlan entities in bulk.
type UsageCardPlanCreateBulk struct {
	config
	err      error
	builders []*UsageCardPlanCreate
	conflict []sql.ConflictOption
}

// Save creates the UsageCardPlan entities in the database.
func (_c *UsageCardPlanCreateBulk) Save(ctx context.Context) ([]*UsageCardPlan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UsageCardPlan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageCardPlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsageCardPlanCreateBulk) SaveX(ctx context.Context) []*UsageCardPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageCardPlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageCardPlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageCardPlan.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageCardPlanUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageCardPlanCreateBulk) OnConflict(opts ...sql.ConflictOption) *UsageCardPlanUpsertBulk {
	_c.conflict = opts
	return &UsageCardPlanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageCardPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageCardPlanCreateBulk) OnConflictColumns(columns ...string) *UsageCardPlanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageCardPlanUpsertBulk{
		create: _c,
	}
}

// UsageCardPlanUpsertBulk is the builder for "upsert"-ing
// a bulk of UsageCardPlan nodes.
type UsageCardPlanUpsertBulk struct {
	create *UsageCardPlanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UsageCardPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageCardPlanUpsertBulk) UpdateNewValues() *UsageCardPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usagecardplan.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageCardPlan.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UsageCardPlanUpsertBulk) Ignore() *UsageCardPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageCardPlanUpsertBulk) DoNothing() *UsageCardPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageCardPlanCreateBulk.OnConflict
// documentation for more info.
func (u *UsageCardPlanUpsertBulk) Update(set func(*UsageCardPlanUpsert)) *UsageCardPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageCardPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *UsageCardPlanUpsertBulk) SetName(v string) *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UsageCardPlanUpsertBulk) UpdateName() *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *UsageCardPlanUpsertBulk) SetDescription(v string) *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *UsageCardPlanUpsertBulk) UpdateDescription() *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateDescription()
	})
}

// SetProductName sets the "product_name" field.
func (u *UsageCardPlanUpsertBulk) SetProductName(v string) *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetProductName(v)
	})
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *UsageCardPlanUpsertBulk) UpdateProductName() *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateProductName()
	})
}

// SetPrice sets the "price" field.
func (u *UsageCardPlanUpsertBulk) SetPrice(v float64) *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *UsageCardPlanUpsertBulk) AddPrice(v float64) *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *UsageCardPlanUpsertBulk) UpdatePrice() *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdatePrice()
	})
}

// SetAmountUsd sets the "amount_usd" field.
func (u *UsageCardPlanUpsertBulk) SetAmountUsd(v float64) *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetAmountUsd(v)
	})
}

// AddAmountUsd adds v to the "amount_usd" field.
func (u *UsageCardPlanUpsertBulk) AddAmountUsd(v float64) *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.AddAmountUsd(v)
	})
}

// UpdateAmountUsd sets the "amount_usd" field to the value that was provided on create.
func (u *UsageCardPlanUpsertBulk) UpdateAmountUsd() *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateAmountUsd()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *UsageCardPlanUpsertBulk) SetValidityDays(v int) *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *UsageCardPlanUpsertBulk) AddValidityDays(v int) *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *UsageCardPlanUpsertBulk) UpdateValidityDays() *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateValidityDays()
	})
}

// SetFeatures sets the "features" field.
func (u *UsageCardPlanUpsertBulk) SetFeatures(v string) *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetFeatures(v)
	})
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *UsageCardPlanUpsertBulk) UpdateFeatures() *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateFeatures()
	})
}

// SetForSale sets the "for_sale" field.
func (u *UsageCardPlanUpsertBulk) SetForSale(v bool) *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetForSale(v)
	})
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *UsageCardPlanUpsertBulk) UpdateForSale() *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateForSale()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *UsageCardPlanUpsertBulk) SetSortOrder(v int) *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *UsageCardPlanUpsertBulk) AddSortOrder(v int) *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *UsageCardPlanUpsertBulk) UpdateSortOrder() *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UsageCardPlanUpsertBulk) SetUpdatedAt(v time.Time) *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UsageCardPlanUpsertBulk) UpdateUpdatedAt() *UsageCardPlanUpsertBulk {
	return u.Update(func(s *UsageCardPlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UsageCardPlanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UsageCardPlanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageCardPlanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageCardPlanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
