// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/usagecardplan"
	"github.com/Wei-Shaw/sub2api/ent/userusagecard"
)

// UsageCardPlanUpdate is the builder for updating UsageCardPlan entities.
type UsageCardPlanUpdate struct {
	config
	hooks    []Hook
	mutation *UsageCardPlanMutation
}

// Where appends a list predicates to the UsageCardPlanUpdate builder.
func (_u *UsageCardPlanUpdate) Where(ps ...predicate.UsageCardPlan) *UsageCardPlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *UsageCardPlanUpdate) SetName(v string) *UsageCardPlanUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UsageCardPlanUpdate) SetNillableName(v *string) *UsageCardPlanUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *UsageCardPlanUpdate) SetDescription(v string) *UsageCardPlanUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *UsageCardPlanUpdate) SetNillableDescription(v *string) *UsageCardPlanUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *UsageCardPlanUpdate) SetPrice(v float64) *UsageCardPlanUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *UsageCardPlanUpdate) SetNillablePrice(v *float64) *UsageCardPlanUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *UsageCardPlanUpdate) AddPrice(v float64) *UsageCardPlanUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetAmountUsd sets the "amount_usd" field.
func (_u *UsageCardPlanUpdate) SetAmountUsd(v float64) *UsageCardPlanUpdate {
	_u.mutation.ResetAmountUsd()
	_u.mutation.SetAmountUsd(v)
	return _u
}

// SetNillableAmountUsd sets the "amount_usd" field if the given value is not nil.
func (_u *UsageCardPlanUpdate) SetNillableAmountUsd(v *float64) *UsageCardPlanUpdate {
	if v != nil {
		_u.SetAmountUsd(*v)
	}
	return _u
}

// AddAmountUsd adds value to the "amount_usd" field.
func (_u *UsageCardPlanUpdate) AddAmountUsd(v float64) *UsageCardPlanUpdate {
	_u.mutation.AddAmountUsd(v)
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *UsageCardPlanUpdate) SetValidityDays(v int) *UsageCardPlanUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *UsageCardPlanUpdate) SetNillableValidityDays(v *int) *UsageCardPlanUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *UsageCardPlanUpdate) AddValidityDays(v int) *UsageCardPlanUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetFeatures sets the "features" field.
func (_u *UsageCardPlanUpdate) SetFeatures(v string) *UsageCardPlanUpdate {
	_u.mutation.SetFeatures(v)
	return _u
}

// SetNillableFeatures sets the "features" field if the given value is not nil.
func (_u *UsageCardPlanUpdate) SetNillableFeatures(v *string) *UsageCardPlanUpdate {
	if v != nil {
		_u.SetFeatures(*v)
	}
	return _u
}

// SetForSale sets the "for_sale" field.
func (_u *UsageCardPlanUpdate) SetForSale(v bool) *UsageCardPlanUpdate {
	_u.mutation.SetForSale(v)
	return _u
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_u *UsageCardPlanUpdate) SetNillableForSale(v *bool) *UsageCardPlanUpdate {
	if v != nil {
		_u.SetForSale(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *UsageCardPlanUpdate) SetSortOrder(v int) *UsageCardPlanUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *UsageCardPlanUpdate) SetNillableSortOrder(v *int) *UsageCardPlanUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *UsageCardPlanUpdate) AddSortOrder(v int) *UsageCardPlanUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsageCardPlanUpdate) SetUpdatedAt(v time.Time) *UsageCardPlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUsageCardIDs adds the "usage_cards" edge to the UserUsageCard entity by IDs.
func (_u *UsageCardPlanUpdate) AddUsageCardIDs(ids ...int64) *UsageCardPlanUpdate {
	_u.mutation.AddUsageCardIDs(ids...)
	return _u
}

// AddUsageCards adds the "usage_cards" edges to the UserUsageCard entity.
func (_u *UsageCardPlanUpdate) AddUsageCards(v ...*UserUsageCard) *UsageCardPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageCardIDs(ids...)
}

// AddRedeemCodeIDs adds the "redeem_codes" edge to the RedeemCode entity by IDs.
func (_u *UsageCardPlanUpdate) AddRedeemCodeIDs(ids ...int64) *UsageCardPlanUpdate {
	_u.mutation.AddRedeemCodeIDs(ids...)
	return _u
}

// AddRedeemCodes adds the "redeem_codes" edges to the RedeemCode entity.
func (_u *UsageCardPlanUpdate) AddRedeemCodes(v ...*RedeemCode) *UsageCardPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRedeemCodeIDs(ids...)
}

// Mutation returns the UsageCardPlanMutation object of the builder.
func (_u *UsageCardPlanUpdate) Mutation() *UsageCardPlanMutation {
	return _u.mutation
}

// ClearUsageCards clears all "usage_cards" edges to the UserUsageCard entity.
func (_u *UsageCardPlanUpdate) ClearUsageCards() *UsageCardPlanUpdate {
	_u.mutation.ClearUsageCards()
	return _u
}

// RemoveUsageCardIDs removes the "usage_cards" edge to UserUsageCard entities by IDs.
func (_u *UsageCardPlanUpdate) RemoveUsageCardIDs(ids ...int64) *UsageCardPlanUpdate {
	_u.mutation.RemoveUsageCardIDs(ids...)
	return _u
}

// RemoveUsageCards removes "usage_cards" edges to UserUsageCard entities.
func (_u *UsageCardPlanUpdate) RemoveUsageCards(v ...*UserUsageCard) *UsageCardPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageCardIDs(ids...)
}

// ClearRedeemCodes clears all "redeem_codes" edges to the RedeemCode entity.
func (_u *UsageCardPlanUpdate) ClearRedeemCodes() *UsageCardPlanUpdate {
	_u.mutation.ClearRedeemCodes()
	return _u
}

// RemoveRedeemCodeIDs removes the "redeem_codes" edge to RedeemCode entities by IDs.
func (_u *UsageCardPlanUpdate) RemoveRedeemCodeIDs(ids ...int64) *UsageCardPlanUpdate {
	_u.mutation.RemoveRedeemCodeIDs(ids...)
	return _u
}

// RemoveRedeemCodes removes "redeem_codes" edges to RedeemCode entities.
func (_u *UsageCardPlanUpdate) RemoveRedeemCodes(v ...*RedeemCode) *UsageCardPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRedeemCodeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageCardPlanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageCardPlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageCardPlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageCardPlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageCardPlanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usagecardplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageCardPlanUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := usagecardplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UsageCardPlan.name": %w`, err)}
		}
	}
	return nil
}

func (_u *UsageCardPlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagecardplan.Table, usagecardplan.Columns, sqlgraph.NewFieldSpec(usagecardplan.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(usagecardplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(usagecardplan.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(usagecardplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(usagecardplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AmountUsd(); ok {
		_spec.SetField(usagecardplan.FieldAmountUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountUsd(); ok {
		_spec.AddField(usagecardplan.FieldAmountUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(usagecardplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(usagecardplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Features(); ok {
		_spec.SetField(usagecardplan.FieldFeatures, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForSale(); ok {
		_spec.SetField(usagecardplan.FieldForSale, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(usagecardplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(usagecardplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usagecardplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsageCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagecardplan.UsageCardsTable,
			Columns: []string{usagecardplan.UsageCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userusagecard.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageCardsIDs(); len(nodes) > 0 && !_u.mutation.UsageCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagecardplan.UsageCardsTable,
			Columns: []string{usagecardplan.UsageCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userusagecard.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageCardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagecardplan.UsageCardsTable,
			Columns: []string{usagecardplan.UsageCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userusagecard.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagecardplan.RedeemCodesTable,
			Columns: []string{usagecardplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRedeemCodesIDs(); len(nodes) > 0 && !_u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagecardplan.RedeemCodesTable,
			Columns: []string{usagecardplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedeemCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagecardplan.RedeemCodesTable,
			Columns: []string{usagecardplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagecardplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageCardPlanUpdateOne is the builder for updating a single UsageCardPlan entity.
type UsageCardPlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageCardPlanMutation
}

// SetName sets the "name" field.
func (_u *UsageCardPlanUpdateOne) SetName(v string) *UsageCardPlanUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UsageCardPlanUpdateOne) SetNillableName(v *string) *UsageCardPlanUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *UsageCardPlanUpdateOne) SetDescription(v string) *UsageCardPlanUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *UsageCardPlanUpdateOne) SetNillableDescription(v *string) *UsageCardPlanUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *UsageCardPlanUpdateOne) SetPrice(v float64) *UsageCardPlanUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *UsageCardPlanUpdateOne) SetNillablePrice(v *float64) *UsageCardPlanUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *UsageCardPlanUpdateOne) AddPrice(v float64) *UsageCardPlanUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetAmountUsd sets the "amount_usd" field.
func (_u *UsageCardPlanUpdateOne) SetAmountUsd(v float64) *UsageCardPlanUpdateOne {
	_u.mutation.ResetAmountUsd()
	_u.mutation.SetAmountUsd(v)
	return _u
}

// SetNillableAmountUsd sets the "amount_usd" field if the given value is not nil.
func (_u *UsageCardPlanUpdateOne) SetNillableAmountUsd(v *float64) *UsageCardPlanUpdateOne {
	if v != nil {
		_u.SetAmountUsd(*v)
	}
	return _u
}

// AddAmountUsd adds value to the "amount_usd" field.
func (_u *UsageCardPlanUpdateOne) AddAmountUsd(v float64) *UsageCardPlanUpdateOne {
	_u.mutation.AddAmountUsd(v)
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *UsageCardPlanUpdateOne) SetValidityDays(v int) *UsageCardPlanUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *UsageCardPlanUpdateOne) SetNillableValidityDays(v *int) *UsageCardPlanUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *UsageCardPlanUpdateOne) AddValidityDays(v int) *UsageCardPlanUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetFeatures sets the "features" field.
func (_u *UsageCardPlanUpdateOne) SetFeatures(v string) *UsageCardPlanUpdateOne {
	_u.mutation.SetFeatures(v)
	return _u
}

// SetNillableFeatures sets the "features" field if the given value is not nil.
func (_u *UsageCardPlanUpdateOne) SetNillableFeatures(v *string) *UsageCardPlanUpdateOne {
	if v != nil {
		_u.SetFeatures(*v)
	}
	return _u
}

// SetForSale sets the "for_sale" field.
func (_u *UsageCardPlanUpdateOne) SetForSale(v bool) *UsageCardPlanUpdateOne {
	_u.mutation.SetForSale(v)
	return _u
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_u *UsageCardPlanUpdateOne) SetNillableForSale(v *bool) *UsageCardPlanUpdateOne {
	if v != nil {
		_u.SetForSale(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *UsageCardPlanUpdateOne) SetSortOrder(v int) *UsageCardPlanUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *UsageCardPlanUpdateOne) SetNillableSortOrder(v *int) *UsageCardPlanUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *UsageCardPlanUpdateOne) AddSortOrder(v int) *UsageCardPlanUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsageCardPlanUpdateOne) SetUpdatedAt(v time.Time) *UsageCardPlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUsageCardIDs adds the "usage_cards" edge to the UserUsageCard entity by IDs.
func (_u *UsageCardPlanUpdateOne) AddUsageCardIDs(ids ...int64) *UsageCardPlanUpdateOne {
	_u.mutation.AddUsageCardIDs(ids...)
	return _u
}

// AddUsageCards adds the "usage_cards" edges to the UserUsageCard entity.
func (_u *UsageCardPlanUpdateOne) AddUsageCards(v ...*UserUsageCard) *UsageCardPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageCardIDs(ids...)
}

// AddRedeemCodeIDs adds the "redeem_codes" edge to the RedeemCode entity by IDs.
func (_u *UsageCardPlanUpdateOne) AddRedeemCodeIDs(ids ...int64) *UsageCardPlanUpdateOne {
	_u.mutation.AddRedeemCodeIDs(ids...)
	return _u
}

// AddRedeemCodes adds the "redeem_codes" edges to the RedeemCode entity.
func (_u *UsageCardPlanUpdateOne) AddRedeemCodes(v ...*RedeemCode) *UsageCardPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRedeemCodeIDs(ids...)
}

// Mutation returns the UsageCardPlanMutation object of the builder.
func (_u *UsageCardPlanUpdateOne) Mutation() *UsageCardPlanMutation {
	return _u.mutation
}

// ClearUsageCards clears all "usage_cards" edges to the UserUsageCard entity.
func (_u *UsageCardPlanUpdateOne) ClearUsageCards() *UsageCardPlanUpdateOne {
	_u.mutation.ClearUsageCards()
	return _u
}

// RemoveUsageCardIDs removes the "usage_cards" edge to UserUsageCard entities by IDs.
func (_u *UsageCardPlanUpdateOne) RemoveUsageCardIDs(ids ...int64) *UsageCardPlanUpdateOne {
	_u.mutation.RemoveUsageCardIDs(ids...)
	return _u
}

// RemoveUsageCards removes "usage_cards" edges to UserUsageCard entities.
func (_u *UsageCardPlanUpdateOne) RemoveUsageCards(v ...*UserUsageCard) *UsageCardPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageCardIDs(ids...)
}

// ClearRedeemCodes clears all "redeem_codes" edges to the RedeemCode entity.
func (_u *UsageCardPlanUpdateOne) ClearRedeemCodes() *UsageCardPlanUpdateOne {
	_u.mutation.ClearRedeemCodes()
	return _u
}

// RemoveRedeemCodeIDs removes the "redeem_codes" edge to RedeemCode entities by IDs.
func (_u *UsageCardPlanUpdateOne) RemoveRedeemCodeIDs(ids ...int64) *UsageCardPlanUpdateOne {
	_u.mutation.RemoveRedeemCodeIDs(ids...)
	return _u
}

// RemoveRedeemCodes removes "redeem_codes" edges to RedeemCode entities.
func (_u *UsageCardPlanUpdateOne) RemoveRedeemCodes(v ...*RedeemCode) *UsageCardPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRedeemCodeIDs(ids...)
}

// Where appends a list predicates to the UsageCardPlanUpdate builder.
func (_u *UsageCardPlanUpdateOne) Where(ps ...predicate.UsageCardPlan) *UsageCardPlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageCardPlanUpdateOne) Select(field string, fields ...string) *UsageCardPlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageCardPlan entity.
func (_u *UsageCardPlanUpdateOne) Save(ctx context.Context) (*UsageCardPlan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageCardPlanUpdateOne) SaveX(ctx context.Context) *UsageCardPlan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageCardPlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageCardPlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageCardPlanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usagecardplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageCardPlanUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := usagecardplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UsageCardPlan.name": %w`, err)}
		}
	}
	return nil
}

func (_u *UsageCardPlanUpdateOne) sqlSave(ctx context.Context) (_node *UsageCardPlan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagecardplan.Table, usagecardplan.Columns, sqlgraph.NewFieldSpec(usagecardplan.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageCardPlan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagecardplan.FieldID)
		for _, f := range fields {
			if !usagecardplan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagecardplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(usagecardplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(usagecardplan.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(usagecardplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(usagecardplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AmountUsd(); ok {
		_spec.SetField(usagecardplan.FieldAmountUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountUsd(); ok {
		_spec.AddField(usagecardplan.FieldAmountUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(usagecardplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(usagecardplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Features(); ok {
		_spec.SetField(usagecardplan.FieldFeatures, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForSale(); ok {
		_spec.SetField(usagecardplan.FieldForSale, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(usagecardplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(usagecardplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usagecardplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsageCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagecardplan.UsageCardsTable,
			Columns: []string{usagecardplan.UsageCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userusagecard.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageCardsIDs(); len(nodes) > 0 && !_u.mutation.UsageCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagecardplan.UsageCardsTable,
			Columns: []string{usagecardplan.UsageCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userusagecard.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageCardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagecardplan.UsageCardsTable,
			Columns: []string{usagecardplan.UsageCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userusagecard.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagecardplan.RedeemCodesTable,
			Columns: []string{usagecardplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRedeemCodesIDs(); len(nodes) > 0 && !_u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagecardplan.RedeemCodesTable,
			Columns: []string{usagecardplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedeemCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagecardplan.RedeemCodesTable,
			Columns: []string{usagecardplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UsageCardPlan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagecardplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
