// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/usagecardplan"
)

// UsageCardPlan is the model entity for the UsageCardPlan schema.
type UsageCardPlan struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// ProductName holds the value of the "product_name" field.
	ProductName string `json:"product_name,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// AmountUsd holds the value of the "amount_usd" field.
	AmountUsd float64 `json:"amount_usd,omitempty"`
	// ValidityDays holds the value of the "validity_days" field.
	ValidityDays int `json:"validity_days,omitempty"`
	// Features holds the value of the "features" field.
	Features string `json:"features,omitempty"`
	// ForSale holds the value of the "for_sale" field.
	ForSale bool `json:"for_sale,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsageCardPlanQuery when eager-loading is set.
	Edges        UsageCardPlanEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UsageCardPlanEdges holds the relations/edges for other nodes in the graph.
type UsageCardPlanEdges struct {
	// UsageCards holds the value of the usage_cards edge.
	UsageCards []*UserUsageCard `json:"usage_cards,omitempty"`
	// RedeemCodes holds the value of the redeem_codes edge.
	RedeemCodes []*RedeemCode `json:"redeem_codes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UsageCardsOrErr returns the UsageCards value or an error if the edge
// was not loaded in eager-loading.
func (e UsageCardPlanEdges) UsageCardsOrErr() ([]*UserUsageCard, error) {
	if e.loadedTypes[0] {
		return e.UsageCards, nil
	}
	return nil, &NotLoadedError{edge: "usage_cards"}
}

// RedeemCodesOrErr returns the RedeemCodes value or an error if the edge
// was not loaded in eager-loading.
func (e UsageCardPlanEdges) RedeemCodesOrErr() ([]*RedeemCode, error) {
	if e.loadedTypes[1] {
		return e.RedeemCodes, nil
	}
	return nil, &NotLoadedError{edge: "redeem_codes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageCardPlan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagecardplan.FieldForSale:
			values[i] = new(sql.NullBool)
		case usagecardplan.FieldPrice, usagecardplan.FieldAmountUsd:
			values[i] = new(sql.NullFloat64)
		case usagecardplan.FieldID, usagecardplan.FieldValidityDays, usagecardplan.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case usagecardplan.FieldName, usagecardplan.FieldDescription, usagecardplan.FieldProductName, usagecardplan.FieldFeatures:
			values[i] = new(sql.NullString)
		case usagecardplan.FieldCreatedAt, usagecardplan.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageCardPlan fields.
func (_m *UsageCardPlan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagecardplan.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usagecardplan.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case usagecardplan.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case usagecardplan.FieldProductName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_name", values[i])
			} else if value.Valid {
				_m.ProductName = value.String
			}
		case usagecardplan.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.Float64
			}
		case usagecardplan.FieldAmountUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_usd", values[i])
			} else if value.Valid {
				_m.AmountUsd = value.Float64
			}
		case usagecardplan.FieldValidityDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field validity_days", values[i])
			} else if value.Valid {
				_m.ValidityDays = int(value.Int64)
			}
		case usagecardplan.FieldFeatures:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field features", values[i])
			} else if value.Valid {
				_m.Features = value.String
			}
		case usagecardplan.FieldForSale:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field for_sale", values[i])
			} else if value.Valid {
				_m.ForSale = value.Bool
			}
		case usagecardplan.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case usagecardplan.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usagecardplan.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageCardPlan.
// This includes values selected through modifiers, order, etc.
func (_m *UsageCardPlan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsageCards queries the "usage_cards" edge of the UsageCardPlan entity.
func (_m *UsageCardPlan) QueryUsageCards() *UserUsageCardQuery {
	return NewUsageCardPlanClient(_m.config).QueryUsageCards(_m)
}

// QueryRedeemCodes queries the "redeem_codes" edge of the UsageCardPlan entity.
func (_m *UsageCardPlan) QueryRedeemCodes() *RedeemCodeQuery {
	return NewUsageCardPlanClient(_m.config).QueryRedeemCodes(_m)
}

// Update returns a builder for updating this UsageCardPlan.
// Note that you need to call UsageCardPlan.Unwrap() before calling this method if this UsageCardPlan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageCardPlan) Update() *UsageCardPlanUpdateOne {
	return NewUsageCardPlanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageCardPlan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageCardPlan) Unwrap() *UsageCardPlan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageCardPlan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageCardPlan) String() string {
	var builder strings.Builder
	builder.WriteString("UsageCardPlan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("product_name=")
	builder.WriteString(_m.ProductName)
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	builder.WriteString("amount_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountUsd))
	builder.WriteString(", ")
	builder.WriteString("validity_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.ValidityDays))
	builder.WriteString(", ")
	builder.WriteString("features=")
	builder.WriteString(_m.Features)
	builder.WriteString(", ")
	builder.WriteString("for_sale=")
	builder.WriteString(fmt.Sprintf("%v", _m.ForSale))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UsageCardPlans is a parsable slice of UsageCardPlan.
type UsageCardPlans []*UsageCardPlan
