// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagecardplan"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userusagecard"
)

// UserUsageCardUpdate is the builder for updating UserUsageCard entities.
type UserUsageCardUpdate struct {
	config
	hooks    []Hook
	mutation *UserUsageCardMutation
}

// Where appends a list predicates to the UserUsageCardUpdate builder.
func (_u *UserUsageCardUpdate) Where(ps ...predicate.UserUsageCard) *UserUsageCardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserUsageCardUpdate) SetDeletedAt(v time.Time) *UserUsageCardUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserUsageCardUpdate) SetNillableDeletedAt(v *time.Time) *UserUsageCardUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserUsageCardUpdate) ClearDeletedAt() *UserUsageCardUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserUsageCardUpdate) SetUserID(v int64) *UserUsageCardUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserUsageCardUpdate) SetNillableUserID(v *int64) *UserUsageCardUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *UserUsageCardUpdate) SetPlanID(v int64) *UserUsageCardUpdate {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *UserUsageCardUpdate) SetNillablePlanID(v *int64) *UserUsageCardUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// ClearPlanID clears the value of the "plan_id" field.
func (_u *UserUsageCardUpdate) ClearPlanID() *UserUsageCardUpdate {
	_u.mutation.ClearPlanID()
	return _u
}

// SetName sets the "name" field.
func (_u *UserUsageCardUpdate) SetName(v string) *UserUsageCardUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUsageCardUpdate) SetNillableName(v *string) *UserUsageCardUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *UserUsageCardUpdate) SetStartsAt(v time.Time) *UserUsageCardUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *UserUsageCardUpdate) SetNillableStartsAt(v *time.Time) *UserUsageCardUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserUsageCardUpdate) SetExpiresAt(v time.Time) *UserUsageCardUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserUsageCardUpdate) SetNillableExpiresAt(v *time.Time) *UserUsageCardUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetTotalLimitUsd sets the "total_limit_usd" field.
func (_u *UserUsageCardUpdate) SetTotalLimitUsd(v float64) *UserUsageCardUpdate {
	_u.mutation.ResetTotalLimitUsd()
	_u.mutation.SetTotalLimitUsd(v)
	return _u
}

// SetNillableTotalLimitUsd sets the "total_limit_usd" field if the given value is not nil.
func (_u *UserUsageCardUpdate) SetNillableTotalLimitUsd(v *float64) *UserUsageCardUpdate {
	if v != nil {
		_u.SetTotalLimitUsd(*v)
	}
	return _u
}

// AddTotalLimitUsd adds value to the "total_limit_usd" field.
func (_u *UserUsageCardUpdate) AddTotalLimitUsd(v float64) *UserUsageCardUpdate {
	_u.mutation.AddTotalLimitUsd(v)
	return _u
}

// SetUsedUsd sets the "used_usd" field.
func (_u *UserUsageCardUpdate) SetUsedUsd(v float64) *UserUsageCardUpdate {
	_u.mutation.ResetUsedUsd()
	_u.mutation.SetUsedUsd(v)
	return _u
}

// SetNillableUsedUsd sets the "used_usd" field if the given value is not nil.
func (_u *UserUsageCardUpdate) SetNillableUsedUsd(v *float64) *UserUsageCardUpdate {
	if v != nil {
		_u.SetUsedUsd(*v)
	}
	return _u
}

// AddUsedUsd adds value to the "used_usd" field.
func (_u *UserUsageCardUpdate) AddUsedUsd(v float64) *UserUsageCardUpdate {
	_u.mutation.AddUsedUsd(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserUsageCardUpdate) SetStatus(v string) *UserUsageCardUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserUsageCardUpdate) SetNillableStatus(v *string) *UserUsageCardUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *UserUsageCardUpdate) SetSource(v string) *UserUsageCardUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *UserUsageCardUpdate) SetNillableSource(v *string) *UserUsageCardUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceOrderID sets the "source_order_id" field.
func (_u *UserUsageCardUpdate) SetSourceOrderID(v int64) *UserUsageCardUpdate {
	_u.mutation.ResetSourceOrderID()
	_u.mutation.SetSourceOrderID(v)
	return _u
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_u *UserUsageCardUpdate) SetNillableSourceOrderID(v *int64) *UserUsageCardUpdate {
	if v != nil {
		_u.SetSourceOrderID(*v)
	}
	return _u
}

// AddSourceOrderID adds value to the "source_order_id" field.
func (_u *UserUsageCardUpdate) AddSourceOrderID(v int64) *UserUsageCardUpdate {
	_u.mutation.AddSourceOrderID(v)
	return _u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (_u *UserUsageCardUpdate) ClearSourceOrderID() *UserUsageCardUpdate {
	_u.mutation.ClearSourceOrderID()
	return _u
}

// SetSourceRedeemCode sets the "source_redeem_code" field.
func (_u *UserUsageCardUpdate) SetSourceRedeemCode(v string) *UserUsageCardUpdate {
	_u.mutation.SetSourceRedeemCode(v)
	return _u
}

// SetNillableSourceRedeemCode sets the "source_redeem_code" field if the given value is not nil.
func (_u *UserUsageCardUpdate) SetNillableSourceRedeemCode(v *string) *UserUsageCardUpdate {
	if v != nil {
		_u.SetSourceRedeemCode(*v)
	}
	return _u
}

// ClearSourceRedeemCode clears the value of the "source_redeem_code" field.
func (_u *UserUsageCardUpdate) ClearSourceRedeemCode() *UserUsageCardUpdate {
	_u.mutation.ClearSourceRedeemCode()
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *UserUsageCardUpdate) SetAssignedBy(v int64) *UserUsageCardUpdate {
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *UserUsageCardUpdate) SetNillableAssignedBy(v *int64) *UserUsageCardUpdate {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (_u *UserUsageCardUpdate) ClearAssignedBy() *UserUsageCardUpdate {
	_u.mutation.ClearAssignedBy()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UserUsageCardUpdate) SetNotes(v string) *UserUsageCardUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UserUsageCardUpdate) SetNillableNotes(v *string) *UserUsageCardUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *UserUsageCardUpdate) ClearNotes() *UserUsageCardUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUsageCardUpdate) SetUpdatedAt(v time.Time) *UserUsageCardUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserUsageCardUpdate) SetUser(v *User) *UserUsageCardUpdate {
	return _u.SetUserID(v.ID)
}

// SetPlan sets the "plan" edge to the UsageCardPlan entity.
func (_u *UserUsageCardUpdate) SetPlan(v *UsageCardPlan) *UserUsageCardUpdate {
	return _u.SetPlanID(v.ID)
}

// SetAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID.
func (_u *UserUsageCardUpdate) SetAssignedByUserID(id int64) *UserUsageCardUpdate {
	_u.mutation.SetAssignedByUserID(id)
	return _u
}

// SetNillableAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *UserUsageCardUpdate) SetNillableAssignedByUserID(id *int64) *UserUsageCardUpdate {
	if id != nil {
		_u = _u.SetAssignedByUserID(*id)
	}
	return _u
}

// SetAssignedByUser sets the "assigned_by_user" edge to the User entity.
func (_u *UserUsageCardUpdate) SetAssignedByUser(v *User) *UserUsageCardUpdate {
	return _u.SetAssignedByUserID(v.ID)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *UserUsageCardUpdate) AddUsageLogIDs(ids ...int64) *UserUsageCardUpdate {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *UserUsageCardUpdate) AddUsageLogs(v ...*UsageLog) *UserUsageCardUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the UserUsageCardMutation object of the builder.
func (_u *UserUsageCardUpdate) Mutation() *UserUsageCardMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserUsageCardUpdate) ClearUser() *UserUsageCardUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearPlan clears the "plan" edge to the UsageCardPlan entity.
func (_u *UserUsageCardUpdate) ClearPlan() *UserUsageCardUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// ClearAssignedByUser clears the "assigned_by_user" edge to the User entity.
func (_u *UserUsageCardUpdate) ClearAssignedByUser() *UserUsageCardUpdate {
	_u.mutation.ClearAssignedByUser()
	return _u
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *UserUsageCardUpdate) ClearUsageLogs() *UserUsageCardUpdate {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *UserUsageCardUpdate) RemoveUsageLogIDs(ids ...int64) *UserUsageCardUpdate {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *UserUsageCardUpdate) RemoveUsageLogs(v ...*UsageLog) *UserUsageCardUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUsageCardUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUsageCardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUsageCardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUsageCardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUsageCardUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if userusagecard.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized userusagecard.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := userusagecard.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUsageCardUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := userusagecard.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserUsageCard.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := userusagecard.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserUsageCard.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := userusagecard.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "UserUsageCard.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceRedeemCode(); ok {
		if err := userusagecard.SourceRedeemCodeValidator(v); err != nil {
			return &ValidationError{Name: "source_redeem_code", err: fmt.Errorf(`ent: validator failed for field "UserUsageCard.source_redeem_code": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserUsageCard.user"`)
	}
	return nil
}

func (_u *UserUsageCardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userusagecard.Table, userusagecard.Columns, sqlgraph.NewFieldSpec(userusagecard.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(userusagecard.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(userusagecard.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(userusagecard.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(userusagecard.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(userusagecard.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TotalLimitUsd(); ok {
		_spec.SetField(userusagecard.FieldTotalLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalLimitUsd(); ok {
		_spec.AddField(userusagecard.FieldTotalLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UsedUsd(); ok {
		_spec.SetField(userusagecard.FieldUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsedUsd(); ok {
		_spec.AddField(userusagecard.FieldUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(userusagecard.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(userusagecard.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceOrderID(); ok {
		_spec.SetField(userusagecard.FieldSourceOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceOrderID(); ok {
		_spec.AddField(userusagecard.FieldSourceOrderID, field.TypeInt64, value)
	}
	if _u.mutation.SourceOrderIDCleared() {
		_spec.ClearField(userusagecard.FieldSourceOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceRedeemCode(); ok {
		_spec.SetField(userusagecard.FieldSourceRedeemCode, field.TypeString, value)
	}
	if _u.mutation.SourceRedeemCodeCleared() {
		_spec.ClearField(userusagecard.FieldSourceRedeemCode, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(userusagecard.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(userusagecard.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userusagecard.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagecard.UserTable,
			Columns: []string{userusagecard.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagecard.UserTable,
			Columns: []string{userusagecard.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagecard.PlanTable,
			Columns: []string{userusagecard.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagecardplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagecard.PlanTable,
			Columns: []string{userusagecard.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagecardplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagecard.AssignedByUserTable,
			Columns: []string{userusagecard.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagecard.AssignedByUserTable,
			Columns: []string{userusagecard.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userusagecard.UsageLogsTable,
			Columns: []string{userusagecard.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userusagecard.UsageLogsTable,
			Columns: []string{userusagecard.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userusagecard.UsageLogsTable,
			Columns: []string{userusagecard.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userusagecard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUsageCardUpdateOne is the builder for updating a single UserUsageCard entity.
type UserUsageCardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserUsageCardMutation
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserUsageCardUpdateOne) SetDeletedAt(v time.Time) *UserUsageCardUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserUsageCardUpdateOne) SetNillableDeletedAt(v *time.Time) *UserUsageCardUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserUsageCardUpdateOne) ClearDeletedAt() *UserUsageCardUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserUsageCardUpdateOne) SetUserID(v int64) *UserUsageCardUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserUsageCardUpdateOne) SetNillableUserID(v *int64) *UserUsageCardUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *UserUsageCardUpdateOne) SetPlanID(v int64) *UserUsageCardUpdateOne {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *UserUsageCardUpdateOne) SetNillablePlanID(v *int64) *UserUsageCardUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// ClearPlanID clears the value of the "plan_id" field.
func (_u *UserUsageCardUpdateOne) ClearPlanID() *UserUsageCardUpdateOne {
	_u.mutation.ClearPlanID()
	return _u
}

// SetName sets the "name" field.
func (_u *UserUsageCardUpdateOne) SetName(v string) *UserUsageCardUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUsageCardUpdateOne) SetNillableName(v *string) *UserUsageCardUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *UserUsageCardUpdateOne) SetStartsAt(v time.Time) *UserUsageCardUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *UserUsageCardUpdateOne) SetNillableStartsAt(v *time.Time) *UserUsageCardUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserUsageCardUpdateOne) SetExpiresAt(v time.Time) *UserUsageCardUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserUsageCardUpdateOne) SetNillableExpiresAt(v *time.Time) *UserUsageCardUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetTotalLimitUsd sets the "total_limit_usd" field.
func (_u *UserUsageCardUpdateOne) SetTotalLimitUsd(v float64) *UserUsageCardUpdateOne {
	_u.mutation.ResetTotalLimitUsd()
	_u.mutation.SetTotalLimitUsd(v)
	return _u
}

// SetNillableTotalLimitUsd sets the "total_limit_usd" field if the given value is not nil.
func (_u *UserUsageCardUpdateOne) SetNillableTotalLimitUsd(v *float64) *UserUsageCardUpdateOne {
	if v != nil {
		_u.SetTotalLimitUsd(*v)
	}
	return _u
}

// AddTotalLimitUsd adds value to the "total_limit_usd" field.
func (_u *UserUsageCardUpdateOne) AddTotalLimitUsd(v float64) *UserUsageCardUpdateOne {
	_u.mutation.AddTotalLimitUsd(v)
	return _u
}

// SetUsedUsd sets the "used_usd" field.
func (_u *UserUsageCardUpdateOne) SetUsedUsd(v float64) *UserUsageCardUpdateOne {
	_u.mutation.ResetUsedUsd()
	_u.mutation.SetUsedUsd(v)
	return _u
}

// SetNillableUsedUsd sets the "used_usd" field if the given value is not nil.
func (_u *UserUsageCardUpdateOne) SetNillableUsedUsd(v *float64) *UserUsageCardUpdateOne {
	if v != nil {
		_u.SetUsedUsd(*v)
	}
	return _u
}

// AddUsedUsd adds value to the "used_usd" field.
func (_u *UserUsageCardUpdateOne) AddUsedUsd(v float64) *UserUsageCardUpdateOne {
	_u.mutation.AddUsedUsd(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserUsageCardUpdateOne) SetStatus(v string) *UserUsageCardUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserUsageCardUpdateOne) SetNillableStatus(v *string) *UserUsageCardUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *UserUsageCardUpdateOne) SetSource(v string) *UserUsageCardUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *UserUsageCardUpdateOne) SetNillableSource(v *string) *UserUsageCardUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceOrderID sets the "source_order_id" field.
func (_u *UserUsageCardUpdateOne) SetSourceOrderID(v int64) *UserUsageCardUpdateOne {
	_u.mutation.ResetSourceOrderID()
	_u.mutation.SetSourceOrderID(v)
	return _u
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_u *UserUsageCardUpdateOne) SetNillableSourceOrderID(v *int64) *UserUsageCardUpdateOne {
	if v != nil {
		_u.SetSourceOrderID(*v)
	}
	return _u
}

// AddSourceOrderID adds value to the "source_order_id" field.
func (_u *UserUsageCardUpdateOne) AddSourceOrderID(v int64) *UserUsageCardUpdateOne {
	_u.mutation.AddSourceOrderID(v)
	return _u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (_u *UserUsageCardUpdateOne) ClearSourceOrderID() *UserUsageCardUpdateOne {
	_u.mutation.ClearSourceOrderID()
	return _u
}

// SetSourceRedeemCode sets the "source_redeem_code" field.
func (_u *UserUsageCardUpdateOne) SetSourceRedeemCode(v string) *UserUsageCardUpdateOne {
	_u.mutation.SetSourceRedeemCode(v)
	return _u
}

// SetNillableSourceRedeemCode sets the "source_redeem_code" field if the given value is not nil.
func (_u *UserUsageCardUpdateOne) SetNillableSourceRedeemCode(v *string) *UserUsageCardUpdateOne {
	if v != nil {
		_u.SetSourceRedeemCode(*v)
	}
	return _u
}

// ClearSourceRedeemCode clears the value of the "source_redeem_code" field.
func (_u *UserUsageCardUpdateOne) ClearSourceRedeemCode() *UserUsageCardUpdateOne {
	_u.mutation.ClearSourceRedeemCode()
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *UserUsageCardUpdateOne) SetAssignedBy(v int64) *UserUsageCardUpdateOne {
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *UserUsageCardUpdateOne) SetNillableAssignedBy(v *int64) *UserUsageCardUpdateOne {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (_u *UserUsageCardUpdateOne) ClearAssignedBy() *UserUsageCardUpdateOne {
	_u.mutation.ClearAssignedBy()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UserUsageCardUpdateOne) SetNotes(v string) *UserUsageCardUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UserUsageCardUpdateOne) SetNillableNotes(v *string) *UserUsageCardUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *UserUsageCardUpdateOne) ClearNotes() *UserUsageCardUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUsageCardUpdateOne) SetUpdatedAt(v time.Time) *UserUsageCardUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserUsageCardUpdateOne) SetUser(v *User) *UserUsageCardUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetPlan sets the "plan" edge to the UsageCardPlan entity.
func (_u *UserUsageCardUpdateOne) SetPlan(v *UsageCardPlan) *UserUsageCardUpdateOne {
	return _u.SetPlanID(v.ID)
}

// SetAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID.
func (_u *UserUsageCardUpdateOne) SetAssignedByUserID(id int64) *UserUsageCardUpdateOne {
	_u.mutation.SetAssignedByUserID(id)
	return _u
}

// SetNillableAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *UserUsageCardUpdateOne) SetNillableAssignedByUserID(id *int64) *UserUsageCardUpdateOne {
	if id != nil {
		_u = _u.SetAssignedByUserID(*id)
	}
	return _u
}

// SetAssignedByUser sets the "assigned_by_user" edge to the User entity.
func (_u *UserUsageCardUpdateOne) SetAssignedByUser(v *User) *UserUsageCardUpdateOne {
	return _u.SetAssignedByUserID(v.ID)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *UserUsageCardUpdateOne) AddUsageLogIDs(ids ...int64) *UserUsageCardUpdateOne {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *UserUsageCardUpdateOne) AddUsageLogs(v ...*UsageLog) *UserUsageCardUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the UserUsageCardMutation object of the builder.
func (_u *UserUsageCardUpdateOne) Mutation() *UserUsageCardMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserUsageCardUpdateOne) ClearUser() *UserUsageCardUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearPlan clears the "plan" edge to the UsageCardPlan entity.
func (_u *UserUsageCardUpdateOne) ClearPlan() *UserUsageCardUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// ClearAssignedByUser clears the "assigned_by_user" edge to the User entity.
func (_u *UserUsageCardUpdateOne) ClearAssignedByUser() *UserUsageCardUpdateOne {
	_u.mutation.ClearAssignedByUser()
	return _u
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *UserUsageCardUpdateOne) ClearUsageLogs() *UserUsageCardUpdateOne {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *UserUsageCardUpdateOne) RemoveUsageLogIDs(ids ...int64) *UserUsageCardUpdateOne {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *UserUsageCardUpdateOne) RemoveUsageLogs(v ...*UsageLog) *UserUsageCardUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Where appends a list predicates to the UserUsageCardUpdate builder.
func (_u *UserUsageCardUpdateOne) Where(ps ...predicate.UserUsageCard) *UserUsageCardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUsageCardUpdateOne) Select(field string, fields ...string) *UserUsageCardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserUsageCard entity.
func (_u *UserUsageCardUpdateOne) Save(ctx context.Context) (*UserUsageCard, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUsageCardUpdateOne) SaveX(ctx context.Context) *UserUsageCard {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUsageCardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUsageCardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUsageCardUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if userusagecard.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized userusagecard.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := userusagecard.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUsageCardUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := userusagecard.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserUsageCard.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := userusagecard.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserUsageCard.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := userusagecard.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "UserUsageCard.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceRedeemCode(); ok {
		if err := userusagecard.SourceRedeemCodeValidator(v); err != nil {
			return &ValidationError{Name: "source_redeem_code", err: fmt.Errorf(`ent: validator failed for field "UserUsageCard.source_redeem_code": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserUsageCard.user"`)
	}
	return nil
}

func (_u *UserUsageCardUpdateOne) sqlSave(ctx context.Context) (_node *UserUsageCard, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userusagecard.Table, userusagecard.Columns, sqlgraph.NewFieldSpec(userusagecard.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserUsageCard.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userusagecard.FieldID)
		for _, f := range fields {
			if !userusagecard.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userusagecard.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(userusagecard.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(userusagecard.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(userusagecard.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(userusagecard.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(userusagecard.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TotalLimitUsd(); ok {
		_spec.SetField(userusagecard.FieldTotalLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalLimitUsd(); ok {
		_spec.AddField(userusagecard.FieldTotalLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UsedUsd(); ok {
		_spec.SetField(userusagecard.FieldUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsedUsd(); ok {
		_spec.AddField(userusagecard.FieldUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(userusagecard.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(userusagecard.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceOrderID(); ok {
		_spec.SetField(userusagecard.FieldSourceOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceOrderID(); ok {
		_spec.AddField(userusagecard.FieldSourceOrderID, field.TypeInt64, value)
	}
	if _u.mutation.SourceOrderIDCleared() {
		_spec.ClearField(userusagecard.FieldSourceOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceRedeemCode(); ok {
		_spec.SetField(userusagecard.FieldSourceRedeemCode, field.TypeString, value)
	}
	if _u.mutation.SourceRedeemCodeCleared() {
		_spec.ClearField(userusagecard.FieldSourceRedeemCode, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(userusagecard.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(userusagecard.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userusagecard.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagecard.UserTable,
			Columns: []string{userusagecard.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagecard.UserTable,
			Columns: []string{userusagecard.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagecard.PlanTable,
			Columns: []string{userusagecard.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagecardplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagecard.PlanTable,
			Columns: []string{userusagecard.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagecardplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagecard.AssignedByUserTable,
			Columns: []string{userusagecard.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagecard.AssignedByUserTable,
			Columns: []string{userusagecard.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userusagecard.UsageLogsTable,
			Columns: []string{userusagecard.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userusagecard.UsageLogsTable,
			Columns: []string{userusagecard.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userusagecard.UsageLogsTable,
			Columns: []string{userusagecard.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserUsageCard{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userusagecard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
