// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/usagecardplan"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userusagecard"
)

// UserUsageCard is the model entity for the UserUsageCard schema.
type UserUsageCard struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID *int64 `json:"plan_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// StartsAt holds the value of the "starts_at" field.
	StartsAt time.Time `json:"starts_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// TotalLimitUsd holds the value of the "total_limit_usd" field.
	TotalLimitUsd float64 `json:"total_limit_usd,omitempty"`
	// UsedUsd holds the value of the "used_usd" field.
	UsedUsd float64 `json:"used_usd,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// SourceOrderID holds the value of the "source_order_id" field.
	SourceOrderID *int64 `json:"source_order_id,omitempty"`
	// SourceRedeemCode holds the value of the "source_redeem_code" field.
	SourceRedeemCode *string `json:"source_redeem_code,omitempty"`
	// AssignedBy holds the value of the "assigned_by" field.
	AssignedBy *int64 `json:"assigned_by,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserUsageCardQuery when eager-loading is set.
	Edges        UserUsageCardEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserUsageCardEdges holds the relations/edges for other nodes in the graph.
type UserUsageCardEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Plan holds the value of the plan edge.
	Plan *UsageCardPlan `json:"plan,omitempty"`
	// AssignedByUser holds the value of the assigned_by_user edge.
	AssignedByUser *User `json:"assigned_by_user,omitempty"`
	// UsageLogs holds the value of the usage_logs edge.
	UsageLogs []*UsageLog `json:"usage_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserUsageCardEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PlanOrErr returns the Plan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserUsageCardEdges) PlanOrErr() (*UsageCardPlan, error) {
	if e.Plan != nil {
		return e.Plan, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: usagecardplan.Label}
	}
	return nil, &NotLoadedError{edge: "plan"}
}

// AssignedByUserOrErr returns the AssignedByUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserUsageCardEdges) AssignedByUserOrErr() (*User, error) {
	if e.AssignedByUser != nil {
		return e.AssignedByUser, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "assigned_by_user"}
}

// UsageLogsOrErr returns the UsageLogs value or an error if the edge
// was not loaded in eager-loading.
func (e UserUsageCardEdges) UsageLogsOrErr() ([]*UsageLog, error) {
	if e.loadedTypes[3] {
		return e.UsageLogs, nil
	}
	return nil, &NotLoadedError{edge: "usage_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserUsageCard) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userusagecard.FieldTotalLimitUsd, userusagecard.FieldUsedUsd:
			values[i] = new(sql.NullFloat64)
		case userusagecard.FieldID, userusagecard.FieldUserID, userusagecard.FieldPlanID, userusagecard.FieldSourceOrderID, userusagecard.FieldAssignedBy:
			values[i] = new(sql.NullInt64)
		case userusagecard.FieldName, userusagecard.FieldStatus, userusagecard.FieldSource, userusagecard.FieldSourceRedeemCode, userusagecard.FieldNotes:
			values[i] = new(sql.NullString)
		case userusagecard.FieldDeletedAt, userusagecard.FieldStartsAt, userusagecard.FieldExpiresAt, userusagecard.FieldCreatedAt, userusagecard.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserUsageCard fields.
func (_m *UserUsageCard) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userusagecard.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case userusagecard.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case userusagecard.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case userusagecard.FieldPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				_m.PlanID = new(int64)
				*_m.PlanID = value.Int64
			}
		case userusagecard.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case userusagecard.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = value.Time
			}
		case userusagecard.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case userusagecard.FieldTotalLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_limit_usd", values[i])
			} else if value.Valid {
				_m.TotalLimitUsd = value.Float64
			}
		case userusagecard.FieldUsedUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field used_usd", values[i])
			} else if value.Valid {
				_m.UsedUsd = value.Float64
			}
		case userusagecard.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case userusagecard.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case userusagecard.FieldSourceOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_order_id", values[i])
			} else if value.Valid {
				_m.SourceOrderID = new(int64)
				*_m.SourceOrderID = value.Int64
			}
		case userusagecard.FieldSourceRedeemCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_redeem_code", values[i])
			} else if value.Valid {
				_m.SourceRedeemCode = new(string)
				*_m.SourceRedeemCode = value.String
			}
		case userusagecard.FieldAssignedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_by", values[i])
			} else if value.Valid {
				_m.AssignedBy = new(int64)
				*_m.AssignedBy = value.Int64
			}
		case userusagecard.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case userusagecard.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userusagecard.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserUsageCard.
// This includes values selected through modifiers, order, etc.
func (_m *UserUsageCard) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserUsageCard entity.
func (_m *UserUsageCard) QueryUser() *UserQuery {
	return NewUserUsageCardClient(_m.config).QueryUser(_m)
}

// QueryPlan queries the "plan" edge of the UserUsageCard entity.
func (_m *UserUsageCard) QueryPlan() *UsageCardPlanQuery {
	return NewUserUsageCardClient(_m.config).QueryPlan(_m)
}

// QueryAssignedByUser queries the "assigned_by_user" edge of the UserUsageCard entity.
func (_m *UserUsageCard) QueryAssignedByUser() *UserQuery {
	return NewUserUsageCardClient(_m.config).QueryAssignedByUser(_m)
}

// QueryUsageLogs queries the "usage_logs" edge of the UserUsageCard entity.
func (_m *UserUsageCard) QueryUsageLogs() *UsageLogQuery {
	return NewUserUsageCardClient(_m.config).QueryUsageLogs(_m)
}

// Update returns a builder for updating this UserUsageCard.
// Note that you need to call UserUsageCard.Unwrap() before calling this method if this UserUsageCard
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserUsageCard) Update() *UserUsageCardUpdateOne {
	return NewUserUsageCardClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserUsageCard entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserUsageCard) Unwrap() *UserUsageCard {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserUsageCard is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserUsageCard) String() string {
	var builder strings.Builder
	builder.WriteString("UserUsageCard(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.PlanID; v != nil {
		builder.WriteString("plan_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("starts_at=")
	builder.WriteString(_m.StartsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("total_limit_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalLimitUsd))
	builder.WriteString(", ")
	builder.WriteString("used_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsedUsd))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	if v := _m.SourceOrderID; v != nil {
		builder.WriteString("source_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SourceRedeemCode; v != nil {
		builder.WriteString("source_redeem_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AssignedBy; v != nil {
		builder.WriteString("assigned_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserUsageCards is a parsable slice of UserUsageCard.
type UserUsageCards []*UserUsageCard
