// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/usagecardplan"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userusagecard"
)

// UserUsageCardCreate is the builder for creating a UserUsageCard entity.
type UserUsageCardCreate struct {
	config
	mutation *UserUsageCardMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UserUsageCardCreate) SetDeletedAt(v time.Time) *UserUsageCardCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UserUsageCardCreate) SetNillableDeletedAt(v *time.Time) *UserUsageCardCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserUsageCardCreate) SetUserID(v int64) *UserUsageCardCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *UserUsageCardCreate) SetPlanID(v int64) *UserUsageCardCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_c *UserUsageCardCreate) SetNillablePlanID(v *int64) *UserUsageCardCreate {
	if v != nil {
		_c.SetPlanID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *UserUsageCardCreate) SetName(v string) *UserUsageCardCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *UserUsageCardCreate) SetNillableName(v *string) *UserUsageCardCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *UserUsageCardCreate) SetStartsAt(v time.Time) *UserUsageCardCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserUsageCardCreate) SetExpiresAt(v time.Time) *UserUsageCardCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetTotalLimitUsd sets the "total_limit_usd" field.
func (_c *UserUsageCardCreate) SetTotalLimitUsd(v float64) *UserUsageCardCreate {
	_c.mutation.SetTotalLimitUsd(v)
	return _c
}

// SetUsedUsd sets the "used_usd" field.
func (_c *UserUsageCardCreate) SetUsedUsd(v float64) *UserUsageCardCreate {
	_c.mutation.SetUsedUsd(v)
	return _c
}

// SetNillableUsedUsd sets the "used_usd" field if the given value is not nil.
func (_c *UserUsageCardCreate) SetNillableUsedUsd(v *float64) *UserUsageCardCreate {
	if v != nil {
		_c.SetUsedUsd(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserUsageCardCreate) SetStatus(v string) *UserUsageCardCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserUsageCardCreate) SetNillableStatus(v *string) *UserUsageCardCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *UserUsageCardCreate) SetSource(v string) *UserUsageCardCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *UserUsageCardCreate) SetNillableSource(v *string) *UserUsageCardCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetSourceOrderID sets the "source_order_id" field.
func (_c *UserUsageCardCreate) SetSourceOrderID(v int64) *UserUsageCardCreate {
	_c.mutation.SetSourceOrderID(v)
	return _c
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_c *UserUsageCardCreate) SetNillableSourceOrderID(v *int64) *UserUsageCardCreate {
	if v != nil {
		_c.SetSourceOrderID(*v)
	}
	return _c
}

// SetSourceRedeemCode sets the "source_redeem_code" field.
func (_c *UserUsageCardCreate) SetSourceRedeemCode(v string) *UserUsageCardCreate {
	_c.mutation.SetSourceRedeemCode(v)
	return _c
}

// SetNillableSourceRedeemCode sets the "source_redeem_code" field if the given value is not nil.
func (_c *UserUsageCardCreate) SetNillableSourceRedeemCode(v *string) *UserUsageCardCreate {
	if v != nil {
		_c.SetSourceRedeemCode(*v)
	}
	return _c
}

// SetAssignedBy sets the "assigned_by" field.
func (_c *UserUsageCardCreate) SetAssignedBy(v int64) *UserUsageCardCreate {
	_c.mutation.SetAssignedBy(v)
	return _c
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_c *UserUsageCardCreate) SetNillableAssignedBy(v *int64) *UserUsageCardCreate {
	if v != nil {
		_c.SetAssignedBy(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *UserUsageCardCreate) SetNotes(v string) *UserUsageCardCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *UserUsageCardCreate) SetNillableNotes(v *string) *UserUsageCardCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserUsageCardCreate) SetCreatedAt(v time.Time) *UserUsageCardCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserUsageCardCreate) SetNillableCreatedAt(v *time.Time) *UserUsageCardCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserUsageCardCreate) SetUpdatedAt(v time.Time) *UserUsageCardCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserUsageCardCreate) SetNillableUpdatedAt(v *time.Time) *UserUsageCardCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserUsageCardCreate) SetUser(v *User) *UserUsageCardCreate {
	return _c.SetUserID(v.ID)
}

// SetPlan sets the "plan" edge to the UsageCardPlan entity.
func (_c *UserUsageCardCreate) SetPlan(v *UsageCardPlan) *UserUsageCardCreate {
	return _c.SetPlanID(v.ID)
}

// SetAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID.
func (_c *UserUsageCardCreate) SetAssignedByUserID(id int64) *UserUsageCardCreate {
	_c.mutation.SetAssignedByUserID(id)
	return _c
}

// SetNillableAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID if the given value is not nil.
func (_c *UserUsageCardCreate) SetNillableAssignedByUserID(id *int64) *UserUsageCardCreate {
	if id != nil {
		_c = _c.SetAssignedByUserID(*id)
	}
	return _c
}

// SetAssignedByUser sets the "assigned_by_user" edge to the User entity.
func (_c *UserUsageCardCreate) SetAssignedByUser(v *User) *UserUsageCardCreate {
	return _c.SetAssignedByUserID(v.ID)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_c *UserUsageCardCreate) AddUsageLogIDs(ids ...int64) *UserUsageCardCreate {
	_c.mutation.AddUsageLogIDs(ids...)
	return _c
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_c *UserUsageCardCreate) AddUsageLogs(v ...*UsageLog) *UserUsageCardCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageLogIDs(ids...)
}

// Mutation returns the UserUsageCardMutation object of the builder.
func (_c *UserUsageCardCreate) Mutation() *UserUsageCardMutation {
	return _c.mutation
}

// Save creates the UserUsageCard in the database.
func (_c *UserUsageCardCreate) Save(ctx context.Context) (*UserUsageCard, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserUsageCardCreate) SaveX(ctx context.Context) *UserUsageCard {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserUsageCardCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserUsageCardCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserUsageCardCreate) defaults() error {
	if _, ok := _c.mutation.Name(); !ok {
		v := userusagecard.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.UsedUsd(); !ok {
		v := userusagecard.DefaultUsedUsd
		_c.mutation.SetUsedUsd(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := userusagecard.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := userusagecard.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if userusagecard.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized userusagecard.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := userusagecard.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if userusagecard.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized userusagecard.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := userusagecard.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserUsageCardCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserUsageCard.user_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UserUsageCard.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := userusagecard.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserUsageCard.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "UserUsageCard.starts_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "UserUsageCard.expires_at"`)}
	}
	if _, ok := _c.mutation.TotalLimitUsd(); !ok {
		return &ValidationError{Name: "total_limit_usd", err: errors.New(`ent: missing required field "UserUsageCard.total_limit_usd"`)}
	}
	if _, ok := _c.mutation.UsedUsd(); !ok {
		return &ValidationError{Name: "used_usd", err: errors.New(`ent: missing required field "UserUsageCard.used_usd"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserUsageCard.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := userusagecard.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserUsageCard.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "UserUsageCard.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := userusagecard.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "UserUsageCard.source": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SourceRedeemCode(); ok {
		if err := userusagecard.SourceRedeemCodeValidator(v); err != nil {
			return &ValidationError{Name: "source_redeem_code", err: fmt.Errorf(`ent: validator failed for field "UserUsageCard.source_redeem_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserUsageCard.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserUsageCard.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserUsageCard.user"`)}
	}
	return nil
}

func (_c *UserUsageCardCreate) sqlSave(ctx context.Context) (*UserUsageCard, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserUsageCardCreate) createSpec() (*UserUsageCard, *sqlgraph.CreateSpec) {
	var (
		_node = &UserUsageCard{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userusagecard.Table, sqlgraph.NewFieldSpec(userusagecard.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(userusagecard.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(userusagecard.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(userusagecard.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(userusagecard.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.TotalLimitUsd(); ok {
		_spec.SetField(userusagecard.FieldTotalLimitUsd, field.TypeFloat64, value)
		_node.TotalLimitUsd = value
	}
	if value, ok := _c.mutation.UsedUsd(); ok {
		_spec.SetField(userusagecard.FieldUsedUsd, field.TypeFloat64, value)
		_node.UsedUsd = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(userusagecard.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(userusagecard.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.SourceOrderID(); ok {
		_spec.SetField(userusagecard.FieldSourceOrderID, field.TypeInt64, value)
		_node.SourceOrderID = &value
	}
	if value, ok := _c.mutation.SourceRedeemCode(); ok {
		_spec.SetField(userusagecard.FieldSourceRedeemCode, field.TypeString, value)
		_node.SourceRedeemCode = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(userusagecard.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userusagecard.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userusagecard.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagecard.UserTable,
			Columns: []string{userusagecard.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagecard.PlanTable,
			Columns: []string{userusagecard.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagecardplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlanID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssignedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagecard.AssignedByUserTable,
			Columns: []string{userusagecard.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AssignedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userusagecard.UsageLogsTable,
			Columns: []string{userusagecard.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserUsageCard.Create().
//		SetDeletedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserUsageCardUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserUsageCardCreate) OnConflict(opts ...sql.ConflictOption) *UserUsageCardUpsertOne {
	_c.conflict = opts
	return &UserUsageCardUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserUsageCard.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserUsageCardCreate) OnConflictColumns(columns ...string) *UserUsageCardUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserUsageCardUpsertOne{
		create: _c,
	}
}

type (
	// UserUsageCardUpsertOne is the builder for "upsert"-ing
	//  one UserUsageCard node.
	UserUsageCardUpsertOne struct {
		create *UserUsageCardCreate
	}

	// UserUsageCardUpsert is the "OnConflict" setter.
	UserUsageCardUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeletedAt sets the "deleted_at" field.
func (u *UserUsageCardUpsert) SetDeletedAt(v time.Time) *UserUsageCardUpsert {
	u.Set(userusagecard.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserUsageCardUpsert) UpdateDeletedAt() *UserUsageCardUpsert {
	u.SetExcluded(userusagecard.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserUsageCardUpsert) ClearDeletedAt() *UserUsageCardUpsert {
	u.SetNull(userusagecard.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserUsageCardUpsert) SetUserID(v int64) *UserUsageCardUpsert {
	u.Set(userusagecard.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserUsageCardUpsert) UpdateUserID() *UserUsageCardUpsert {
	u.SetExcluded(userusagecard.FieldUserID)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *UserUsageCardUpsert) SetPlanID(v int64) *UserUsageCardUpsert {
	u.Set(userusagecard.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UserUsageCardUpsert) UpdatePlanID() *UserUsageCardUpsert {
	u.SetExcluded(userusagecard.FieldPlanID)
	return u
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *UserUsageCardUpsert) ClearPlanID() *UserUsageCardUpsert {
	u.SetNull(userusagecard.FieldPlanID)
	return u
}

// SetName sets the "name" field.
func (u *UserUsageCardUpsert) SetName(v string) *UserUsageCardUpsert {
	u.Set(userusagecard.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserUsageCardUpsert) UpdateName() *UserUsageCardUpsert {
	u.SetExcluded(userusagecard.FieldName)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *UserUsageCardUpsert) SetStartsAt(v time.Time) *UserUsageCardUpsert {
	u.Set(userusagecard.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserUsageCardUpsert) UpdateStartsAt() *UserUsageCardUpsert {
	u.SetExcluded(userusagecard.FieldStartsAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserUsageCardUpsert) SetExpiresAt(v time.Time) *UserUsageCardUpsert {
	u.Set(userusagecard.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserUsageCardUpsert) UpdateExpiresAt() *UserUsageCardUpsert {
	u.SetExcluded(userusagecard.FieldExpiresAt)
	return u
}

// SetTotalLimitUsd sets the "total_limit_usd" field.
func (u *UserUsageCardUpsert) SetTotalLimitUsd(v float64) *UserUsageCardUpsert {
	u.Set(userusagecard.FieldTotalLimitUsd, v)
	return u
}

// UpdateTotalLimitUsd sets the "total_limit_usd" field to the value that was provided on create.
func (u *UserUsageCardUpsert) UpdateTotalLimitUsd() *UserUsageCardUpsert {
	u.SetExcluded(userusagecard.FieldTotalLimitUsd)
	return u
}

// AddTotalLimitUsd adds v to the "total_limit_usd" field.
func (u *UserUsageCardUpsert) AddTotalLimitUsd(v float64) *UserUsageCardUpsert {
	u.Add(userusagecard.FieldTotalLimitUsd, v)
	return u
}

// SetUsedUsd sets the "used_usd" field.
func (u *UserUsageCardUpsert) SetUsedUsd(v float64) *UserUsageCardUpsert {
	u.Set(userusagecard.FieldUsedUsd, v)
	return u
}

// UpdateUsedUsd sets the "used_usd" field to the value that was provided on create.
func (u *UserUsageCardUpsert) UpdateUsedUsd() *UserUsageCardUpsert {
	u.SetExcluded(userusagecard.FieldUsedUsd)
	return u
}

// AddUsedUsd adds v to the "used_usd" field.
func (u *UserUsageCardUpsert) AddUsedUsd(v float64) *UserUsageCardUpsert {
	u.Add(userusagecard.FieldUsedUsd, v)
	return u
}

// SetStatus sets the "status" field.
func (u *UserUsageCardUpsert) SetStatus(v string) *UserUsageCardUpsert {
	u.Set(userusagecard.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserUsageCardUpsert) UpdateStatus() *UserUsageCardUpsert {
	u.SetExcluded(userusagecard.FieldStatus)
	return u
}

// SetSource sets the "source" field.
func (u *UserUsageCardUpsert) SetSource(v string) *UserUsageCardUpsert {
	u.Set(userusagecard.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *UserUsageCardUpsert) UpdateSource() *UserUsageCardUpsert {
	u.SetExcluded(userusagecard.FieldSource)
	return u
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *UserUsageCardUpsert) SetSourceOrderID(v int64) *UserUsageCardUpsert {
	u.Set(userusagecard.FieldSourceOrderID, v)
	return u
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *UserUsageCardUpsert) UpdateSourceOrderID() *UserUsageCardUpsert {
	u.SetExcluded(userusagecard.FieldSourceOrderID)
	return u
}

// AddSourceOrderID adds v to the "source_order_id" field.
func (u *UserUsageCardUpsert) AddSourceOrderID(v int64) *UserUsageCardUpsert {
	u.Add(userusagecard.FieldSourceOrderID, v)
	return u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *UserUsageCardUpsert) ClearSourceOrderID() *UserUsageCardUpsert {
	u.SetNull(userusagecard.FieldSourceOrderID)
	return u
}

// SetSourceRedeemCode sets the "source_redeem_code" field.
func (u *UserUsageCardUpsert) SetSourceRedeemCode(v string) *UserUsageCardUpsert {
	u.Set(userusagecard.FieldSourceRedeemCode, v)
	return u
}

// UpdateSourceRedeemCode sets the "source_redeem_code" field to the value that was provided on create.
func (u *UserUsageCardUpsert) UpdateSourceRedeemCode() *UserUsageCardUpsert {
	u.SetExcluded(userusagecard.FieldSourceRedeemCode)
	return u
}

// ClearSourceRedeemCode clears the value of the "source_redeem_code" field.
func (u *UserUsageCardUpsert) ClearSourceRedeemCode() *UserUsageCardUpsert {
	u.SetNull(userusagecard.FieldSourceRedeemCode)
	return u
}

// SetAssignedBy sets the "assigned_by" field.
func (u *UserUsageCardUpsert) SetAssignedBy(v int64) *UserUsageCardUpsert {
	u.Set(userusagecard.FieldAssignedBy, v)
	return u
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *UserUsageCardUpsert) UpdateAssignedBy() *UserUsageCardUpsert {
	u.SetExcluded(userusagecard.FieldAssignedBy)
	return u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *UserUsageCardUpsert) ClearAssignedBy() *UserUsageCardUpsert {
	u.SetNull(userusagecard.FieldAssignedBy)
	return u
}

// SetNotes sets the "notes" field.
func (u *UserUsageCardUpsert) SetNotes(v string) *UserUsageCardUpsert {
	u.Set(userusagecard.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserUsageCardUpsert) UpdateNotes() *UserUsageCardUpsert {
	u.SetExcluded(userusagecard.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *UserUsageCardUpsert) ClearNotes() *UserUsageCardUpsert {
	u.SetNull(userusagecard.FieldNotes)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserUsageCardUpsert) SetUpdatedAt(v time.Time) *UserUsageCardUpsert {
	u.Set(userusagecard.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserUsageCardUpsert) UpdateUpdatedAt() *UserUsageCardUpsert {
	u.SetExcluded(userusagecard.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserUsageCard.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserUsageCardUpsertOne) UpdateNewValues() *UserUsageCardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userusagecard.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserUsageCard.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserUsageCardUpsertOne) Ignore() *UserUsageCardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserUsageCardUpsertOne) DoNothing() *UserUsageCardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserUsageCardCreate.OnConflict
// documentation for more info.
func (u *UserUsageCardUpsertOne) Update(set func(*UserUsageCardUpsert)) *UserUsageCardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserUsageCardUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserUsageCardUpsertOne) SetDeletedAt(v time.Time) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserUsageCardUpsertOne) UpdateDeletedAt() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserUsageCardUpsertOne) ClearDeletedAt() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserUsageCardUpsertOne) SetUserID(v int64) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserUsageCardUpsertOne) UpdateUserID() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateUserID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *UserUsageCardUpsertOne) SetPlanID(v int64) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UserUsageCardUpsertOne) UpdatePlanID() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdatePlanID()
	})
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *UserUsageCardUpsertOne) ClearPlanID() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.ClearPlanID()
	})
}

// SetName sets the "name" field.
func (u *UserUsageCardUpsertOne) SetName(v string) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserUsageCardUpsertOne) UpdateName() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateName()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserUsageCardUpsertOne) SetStartsAt(v time.Time) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserUsageCardUpsertOne) UpdateStartsAt() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserUsageCardUpsertOne) SetExpiresAt(v time.Time) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserUsageCardUpsertOne) UpdateExpiresAt() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetTotalLimitUsd sets the "total_limit_usd" field.
func (u *UserUsageCardUpsertOne) SetTotalLimitUsd(v float64) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetTotalLimitUsd(v)
	})
}

// AddTotalLimitUsd adds v to the "total_limit_usd" field.
func (u *UserUsageCardUpsertOne) AddTotalLimitUsd(v float64) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.AddTotalLimitUsd(v)
	})
}

// UpdateTotalLimitUsd sets the "total_limit_usd" field to the value that was provided on create.
func (u *UserUsageCardUpsertOne) UpdateTotalLimitUsd() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateTotalLimitUsd()
	})
}

// SetUsedUsd sets the "used_usd" field.
func (u *UserUsageCardUpsertOne) SetUsedUsd(v float64) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetUsedUsd(v)
	})
}

// AddUsedUsd adds v to the "used_usd" field.
func (u *UserUsageCardUpsertOne) AddUsedUsd(v float64) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.AddUsedUsd(v)
	})
}

// UpdateUsedUsd sets the "used_usd" field to the value that was provided on create.
func (u *UserUsageCardUpsertOne) UpdateUsedUsd() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateUsedUsd()
	})
}

// SetStatus sets the "status" field.
func (u *UserUsageCardUpsertOne) SetStatus(v string) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserUsageCardUpsertOne) UpdateStatus() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateStatus()
	})
}

// SetSource sets the "source" field.
func (u *UserUsageCardUpsertOne) SetSource(v string) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *UserUsageCardUpsertOne) UpdateSource() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateSource()
	})
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *UserUsageCardUpsertOne) SetSourceOrderID(v int64) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetSourceOrderID(v)
	})
}

// AddSourceOrderID adds v to the "source_order_id" field.
func (u *UserUsageCardUpsertOne) AddSourceOrderID(v int64) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.AddSourceOrderID(v)
	})
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *UserUsageCardUpsertOne) UpdateSourceOrderID() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateSourceOrderID()
	})
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *UserUsageCardUpsertOne) ClearSourceOrderID() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.ClearSourceOrderID()
	})
}

// SetSourceRedeemCode sets the "source_redeem_code" field.
func (u *UserUsageCardUpsertOne) SetSourceRedeemCode(v string) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetSourceRedeemCode(v)
	})
}

// UpdateSourceRedeemCode sets the "source_redeem_code" field to the value that was provided on create.
func (u *UserUsageCardUpsertOne) UpdateSourceRedeemCode() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateSourceRedeemCode()
	})
}

// ClearSourceRedeemCode clears the value of the "source_redeem_code" field.
func (u *UserUsageCardUpsertOne) ClearSourceRedeemCode() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.ClearSourceRedeemCode()
	})
}

// SetAssignedBy sets the "assigned_by" field.
func (u *UserUsageCardUpsertOne) SetAssignedBy(v int64) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetAssignedBy(v)
	})
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *UserUsageCardUpsertOne) UpdateAssignedBy() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateAssignedBy()
	})
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *UserUsageCardUpsertOne) ClearAssignedBy() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.ClearAssignedBy()
	})
}

// SetNotes sets the "notes" field.
func (u *UserUsageCardUpsertOne) SetNotes(v string) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserUsageCardUpsertOne) UpdateNotes() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *UserUsageCardUpsertOne) ClearNotes() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserUsageCardUpsertOne) SetUpdatedAt(v time.Time) *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserUsageCardUpsertOne) UpdateUpdatedAt() *UserUsageCardUpsertOne {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserUsageCardUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserUsageCardCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserUsageCardUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserUsageCardUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserUsageCardUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserUsageCardCreateBulk is the builder for creating many UserUsageCard entities in bulk.
type UserUsageCardCreateBulk struct {
	config
	err      error
	builders []*UserUsageCardCreate
	conflict []sql.ConflictOption
}

// Save creates the UserUsageCard entities in the database.
func (_c *UserUsageCardCreateBulk) Save(ctx context.Context) ([]*UserUsageCard, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserUsageCard, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserUsageCardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserUsageCardCreateBulk) SaveX(ctx context.Context) []*UserUsageCard {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserUsageCardCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserUsageCardCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserUsageCard.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserUsageCardUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserUsageCardCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserUsageCardUpsertBulk {
	_c.conflict = opts
	return &UserUsageCardUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserUsageCard.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserUsageCardCreateBulk) OnConflictColumns(columns ...string) *UserUsageCardUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserUsageCardUpsertBulk{
		create: _c,
	}
}

// UserUsageCardUpsertBulk is the builder for "upsert"-ing
// a bulk of UserUsageCard nodes.
type UserUsageCardUpsertBulk struct {
	create *UserUsageCardCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserUsageCard.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserUsageCardUpsertBulk) UpdateNewValues() *UserUsageCardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userusagecard.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserUsageCard.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserUsageCardUpsertBulk) Ignore() *UserUsageCardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserUsageCardUpsertBulk) DoNothing() *UserUsageCardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserUsageCardCreateBulk.OnConflict
// documentation for more info.
func (u *UserUsageCardUpsertBulk) Update(set func(*UserUsageCardUpsert)) *UserUsageCardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserUsageCardUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserUsageCardUpsertBulk) SetDeletedAt(v time.Time) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserUsageCardUpsertBulk) UpdateDeletedAt() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserUsageCardUpsertBulk) ClearDeletedAt() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserUsageCardUpsertBulk) SetUserID(v int64) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserUsageCardUpsertBulk) UpdateUserID() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateUserID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *UserUsageCardUpsertBulk) SetPlanID(v int64) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UserUsageCardUpsertBulk) UpdatePlanID() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdatePlanID()
	})
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *UserUsageCardUpsertBulk) ClearPlanID() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.ClearPlanID()
	})
}

// SetName sets the "name" field.
func (u *UserUsageCardUpsertBulk) SetName(v string) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserUsageCardUpsertBulk) UpdateName() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateName()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserUsageCardUpsertBulk) SetStartsAt(v time.Time) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserUsageCardUpsertBulk) UpdateStartsAt() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserUsageCardUpsertBulk) SetExpiresAt(v time.Time) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserUsageCardUpsertBulk) UpdateExpiresAt() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetTotalLimitUsd sets the "total_limit_usd" field.
func (u *UserUsageCardUpsertBulk) SetTotalLimitUsd(v float64) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetTotalLimitUsd(v)
	})
}

// AddTotalLimitUsd adds v to the "total_limit_usd" field.
func (u *UserUsageCardUpsertBulk) AddTotalLimitUsd(v float64) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.AddTotalLimitUsd(v)
	})
}

// UpdateTotalLimitUsd sets the "total_limit_usd" field to the value that was provided on create.
func (u *UserUsageCardUpsertBulk) UpdateTotalLimitUsd() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateTotalLimitUsd()
	})
}

// SetUsedUsd sets the "used_usd" field.
func (u *UserUsageCardUpsertBulk) SetUsedUsd(v float64) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetUsedUsd(v)
	})
}

// AddUsedUsd adds v to the "used_usd" field.
func (u *UserUsageCardUpsertBulk) AddUsedUsd(v float64) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.AddUsedUsd(v)
	})
}

// UpdateUsedUsd sets the "used_usd" field to the value that was provided on create.
func (u *UserUsageCardUpsertBulk) UpdateUsedUsd() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateUsedUsd()
	})
}

// SetStatus sets the "status" field.
func (u *UserUsageCardUpsertBulk) SetStatus(v string) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserUsageCardUpsertBulk) UpdateStatus() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateStatus()
	})
}

// SetSource sets the "source" field.
func (u *UserUsageCardUpsertBulk) SetSource(v string) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *UserUsageCardUpsertBulk) UpdateSource() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateSource()
	})
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *UserUsageCardUpsertBulk) SetSourceOrderID(v int64) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetSourceOrderID(v)
	})
}

// AddSourceOrderID adds v to the "source_order_id" field.
func (u *UserUsageCardUpsertBulk) AddSourceOrderID(v int64) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.AddSourceOrderID(v)
	})
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *UserUsageCardUpsertBulk) UpdateSourceOrderID() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateSourceOrderID()
	})
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *UserUsageCardUpsertBulk) ClearSourceOrderID() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.ClearSourceOrderID()
	})
}

// SetSourceRedeemCode sets the "source_redeem_code" field.
func (u *UserUsageCardUpsertBulk) SetSourceRedeemCode(v string) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetSourceRedeemCode(v)
	})
}

// UpdateSourceRedeemCode sets the "source_redeem_code" field to the value that was provided on create.
func (u *UserUsageCardUpsertBulk) UpdateSourceRedeemCode() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateSourceRedeemCode()
	})
}

// ClearSourceRedeemCode clears the value of the "source_redeem_code" field.
func (u *UserUsageCardUpsertBulk) ClearSourceRedeemCode() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.ClearSourceRedeemCode()
	})
}

// SetAssignedBy sets the "assigned_by" field.
func (u *UserUsageCardUpsertBulk) SetAssignedBy(v int64) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetAssignedBy(v)
	})
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *UserUsageCardUpsertBulk) UpdateAssignedBy() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateAssignedBy()
	})
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *UserUsageCardUpsertBulk) ClearAssignedBy() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.ClearAssignedBy()
	})
}

// SetNotes sets the "notes" field.
func (u *UserUsageCardUpsertBulk) SetNotes(v string) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserUsageCardUpsertBulk) UpdateNotes() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *UserUsageCardUpsertBulk) ClearNotes() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserUsageCardUpsertBulk) SetUpdatedAt(v time.Time) *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserUsageCardUpsertBulk) UpdateUpdatedAt() *UserUsageCardUpsertBulk {
	return u.Update(func(s *UserUsageCardUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserUsageCardUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserUsageCardCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserUsageCardCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserUsageCardUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
