// Code generated by ent, DO NOT EDIT.

package userusagecard

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLTE(FieldID, id))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldUserID, v))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldPlanID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldName, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldStartsAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldExpiresAt, v))
}

// TotalLimitUsd applies equality check predicate on the "total_limit_usd" field. It's identical to TotalLimitUsdEQ.
func TotalLimitUsd(v float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldTotalLimitUsd, v))
}

// UsedUsd applies equality check predicate on the "used_usd" field. It's identical to UsedUsdEQ.
func UsedUsd(v float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldUsedUsd, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldStatus, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldSource, v))
}

// SourceOrderID applies equality check predicate on the "source_order_id" field. It's identical to SourceOrderIDEQ.
func SourceOrderID(v int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldSourceOrderID, v))
}

// SourceRedeemCode applies equality check predicate on the "source_redeem_code" field. It's identical to SourceRedeemCodeEQ.
func SourceRedeemCode(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldSourceRedeemCode, v))
}

// AssignedBy applies equality check predicate on the "assigned_by" field. It's identical to AssignedByEQ.
func AssignedBy(v int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldAssignedBy, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotIn(FieldUserID, vs...))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotIn(FieldPlanID, vs...))
}

// PlanIDIsNil applies the IsNil predicate on the "plan_id" field.
func PlanIDIsNil() predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIsNull(FieldPlanID))
}

// PlanIDNotNil applies the NotNil predicate on the "plan_id" field.
func PlanIDNotNil() predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotNull(FieldPlanID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldContainsFold(FieldName, v))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLTE(FieldStartsAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLTE(FieldExpiresAt, v))
}

// TotalLimitUsdEQ applies the EQ predicate on the "total_limit_usd" field.
func TotalLimitUsdEQ(v float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldTotalLimitUsd, v))
}

// TotalLimitUsdNEQ applies the NEQ predicate on the "total_limit_usd" field.
func TotalLimitUsdNEQ(v float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNEQ(FieldTotalLimitUsd, v))
}

// TotalLimitUsdIn applies the In predicate on the "total_limit_usd" field.
func TotalLimitUsdIn(vs ...float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIn(FieldTotalLimitUsd, vs...))
}

// TotalLimitUsdNotIn applies the NotIn predicate on the "total_limit_usd" field.
func TotalLimitUsdNotIn(vs ...float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotIn(FieldTotalLimitUsd, vs...))
}

// TotalLimitUsdGT applies the GT predicate on the "total_limit_usd" field.
func TotalLimitUsdGT(v float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGT(FieldTotalLimitUsd, v))
}

// TotalLimitUsdGTE applies the GTE predicate on the "total_limit_usd" field.
func TotalLimitUsdGTE(v float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGTE(FieldTotalLimitUsd, v))
}

// TotalLimitUsdLT applies the LT predicate on the "total_limit_usd" field.
func TotalLimitUsdLT(v float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLT(FieldTotalLimitUsd, v))
}

// TotalLimitUsdLTE applies the LTE predicate on the "total_limit_usd" field.
func TotalLimitUsdLTE(v float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLTE(FieldTotalLimitUsd, v))
}

// UsedUsdEQ applies the EQ predicate on the "used_usd" field.
func UsedUsdEQ(v float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldUsedUsd, v))
}

// UsedUsdNEQ applies the NEQ predicate on the "used_usd" field.
func UsedUsdNEQ(v float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNEQ(FieldUsedUsd, v))
}

// UsedUsdIn applies the In predicate on the "used_usd" field.
func UsedUsdIn(vs ...float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIn(FieldUsedUsd, vs...))
}

// UsedUsdNotIn applies the NotIn predicate on the "used_usd" field.
func UsedUsdNotIn(vs ...float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotIn(FieldUsedUsd, vs...))
}

// UsedUsdGT applies the GT predicate on the "used_usd" field.
func UsedUsdGT(v float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGT(FieldUsedUsd, v))
}

// UsedUsdGTE applies the GTE predicate on the "used_usd" field.
func UsedUsdGTE(v float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGTE(FieldUsedUsd, v))
}

// UsedUsdLT applies the LT predicate on the "used_usd" field.
func UsedUsdLT(v float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLT(FieldUsedUsd, v))
}

// UsedUsdLTE applies the LTE predicate on the "used_usd" field.
func UsedUsdLTE(v float64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLTE(FieldUsedUsd, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldContainsFold(FieldStatus, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldContainsFold(FieldSource, v))
}

// SourceOrderIDEQ applies the EQ predicate on the "source_order_id" field.
func SourceOrderIDEQ(v int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldSourceOrderID, v))
}

// SourceOrderIDNEQ applies the NEQ predicate on the "source_order_id" field.
func SourceOrderIDNEQ(v int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNEQ(FieldSourceOrderID, v))
}

// SourceOrderIDIn applies the In predicate on the "source_order_id" field.
func SourceOrderIDIn(vs ...int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIn(FieldSourceOrderID, vs...))
}

// SourceOrderIDNotIn applies the NotIn predicate on the "source_order_id" field.
func SourceOrderIDNotIn(vs ...int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotIn(FieldSourceOrderID, vs...))
}

// SourceOrderIDGT applies the GT predicate on the "source_order_id" field.
func SourceOrderIDGT(v int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGT(FieldSourceOrderID, v))
}

// SourceOrderIDGTE applies the GTE predicate on the "source_order_id" field.
func SourceOrderIDGTE(v int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGTE(FieldSourceOrderID, v))
}

// SourceOrderIDLT applies the LT predicate on the "source_order_id" field.
func SourceOrderIDLT(v int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLT(FieldSourceOrderID, v))
}

// SourceOrderIDLTE applies the LTE predicate on the "source_order_id" field.
func SourceOrderIDLTE(v int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLTE(FieldSourceOrderID, v))
}

// SourceOrderIDIsNil applies the IsNil predicate on the "source_order_id" field.
func SourceOrderIDIsNil() predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIsNull(FieldSourceOrderID))
}

// SourceOrderIDNotNil applies the NotNil predicate on the "source_order_id" field.
func SourceOrderIDNotNil() predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotNull(FieldSourceOrderID))
}

// SourceRedeemCodeEQ applies the EQ predicate on the "source_redeem_code" field.
func SourceRedeemCodeEQ(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeNEQ applies the NEQ predicate on the "source_redeem_code" field.
func SourceRedeemCodeNEQ(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNEQ(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeIn applies the In predicate on the "source_redeem_code" field.
func SourceRedeemCodeIn(vs ...string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIn(FieldSourceRedeemCode, vs...))
}

// SourceRedeemCodeNotIn applies the NotIn predicate on the "source_redeem_code" field.
func SourceRedeemCodeNotIn(vs ...string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotIn(FieldSourceRedeemCode, vs...))
}

// SourceRedeemCodeGT applies the GT predicate on the "source_redeem_code" field.
func SourceRedeemCodeGT(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGT(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeGTE applies the GTE predicate on the "source_redeem_code" field.
func SourceRedeemCodeGTE(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGTE(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeLT applies the LT predicate on the "source_redeem_code" field.
func SourceRedeemCodeLT(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLT(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeLTE applies the LTE predicate on the "source_redeem_code" field.
func SourceRedeemCodeLTE(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLTE(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeContains applies the Contains predicate on the "source_redeem_code" field.
func SourceRedeemCodeContains(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldContains(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeHasPrefix applies the HasPrefix predicate on the "source_redeem_code" field.
func SourceRedeemCodeHasPrefix(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldHasPrefix(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeHasSuffix applies the HasSuffix predicate on the "source_redeem_code" field.
func SourceRedeemCodeHasSuffix(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldHasSuffix(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeIsNil applies the IsNil predicate on the "source_redeem_code" field.
func SourceRedeemCodeIsNil() predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIsNull(FieldSourceRedeemCode))
}

// SourceRedeemCodeNotNil applies the NotNil predicate on the "source_redeem_code" field.
func SourceRedeemCodeNotNil() predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotNull(FieldSourceRedeemCode))
}

// SourceRedeemCodeEqualFold applies the EqualFold predicate on the "source_redeem_code" field.
func SourceRedeemCodeEqualFold(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEqualFold(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeContainsFold applies the ContainsFold predicate on the "source_redeem_code" field.
func SourceRedeemCodeContainsFold(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldContainsFold(FieldSourceRedeemCode, v))
}

// AssignedByEQ applies the EQ predicate on the "assigned_by" field.
func AssignedByEQ(v int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldAssignedBy, v))
}

// AssignedByNEQ applies the NEQ predicate on the "assigned_by" field.
func AssignedByNEQ(v int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNEQ(FieldAssignedBy, v))
}

// AssignedByIn applies the In predicate on the "assigned_by" field.
func AssignedByIn(vs ...int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIn(FieldAssignedBy, vs...))
}

// AssignedByNotIn applies the NotIn predicate on the "assigned_by" field.
func AssignedByNotIn(vs ...int64) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotIn(FieldAssignedBy, vs...))
}

// AssignedByIsNil applies the IsNil predicate on the "assigned_by" field.
func AssignedByIsNil() predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIsNull(FieldAssignedBy))
}

// AssignedByNotNil applies the NotNil predicate on the "assigned_by" field.
func AssignedByNotNil() predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotNull(FieldAssignedBy))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserUsageCard {
	return predicate.UserUsageCard(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserUsageCard {
	return predicate.UserUsageCard(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlan applies the HasEdge predicate on the "plan" edge.
func HasPlan() predicate.UserUsageCard {
	return predicate.UserUsageCard(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlanTable, PlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlanWith applies the HasEdge predicate on the "plan" edge with a given conditions (other predicates).
func HasPlanWith(preds ...predicate.UsageCardPlan) predicate.UserUsageCard {
	return predicate.UserUsageCard(func(s *sql.Selector) {
		step := newPlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssignedByUser applies the HasEdge predicate on the "assigned_by_user" edge.
func HasAssignedByUser() predicate.UserUsageCard {
	return predicate.UserUsageCard(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AssignedByUserTable, AssignedByUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignedByUserWith applies the HasEdge predicate on the "assigned_by_user" edge with a given conditions (other predicates).
func HasAssignedByUserWith(preds ...predicate.User) predicate.UserUsageCard {
	return predicate.UserUsageCard(func(s *sql.Selector) {
		step := newAssignedByUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageLogs applies the HasEdge predicate on the "usage_logs" edge.
func HasUsageLogs() predicate.UserUsageCard {
	return predicate.UserUsageCard(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogsWith applies the HasEdge predicate on the "usage_logs" edge with a given conditions (other predicates).
func HasUsageLogsWith(preds ...predicate.UsageLog) predicate.UserUsageCard {
	return predicate.UserUsageCard(func(s *sql.Selector) {
		step := newUsageLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserUsageCard) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserUsageCard) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserUsageCard) predicate.UserUsageCard {
	return predicate.UserUsageCard(sql.NotPredicates(p))
}
