// Code generated by ent, DO NOT EDIT.

package usagecardplan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldDescription, v))
}

// ProductName applies equality check predicate on the "product_name" field. It's identical to ProductNameEQ.
func ProductName(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldProductName, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldPrice, v))
}

// AmountUsd applies equality check predicate on the "amount_usd" field. It's identical to AmountUsdEQ.
func AmountUsd(v float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldAmountUsd, v))
}

// ValidityDays applies equality check predicate on the "validity_days" field. It's identical to ValidityDaysEQ.
func ValidityDays(v int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldValidityDays, v))
}

// Features applies equality check predicate on the "features" field. It's identical to FeaturesEQ.
func Features(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldFeatures, v))
}

// ForSale applies equality check predicate on the "for_sale" field. It's identical to ForSaleEQ.
func ForSale(v bool) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldForSale, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldContainsFold(FieldDescription, v))
}

// ProductNameEQ applies the EQ predicate on the "product_name" field.
func ProductNameEQ(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldProductName, v))
}

// ProductNameNEQ applies the NEQ predicate on the "product_name" field.
func ProductNameNEQ(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNEQ(FieldProductName, v))
}

// ProductNameIn applies the In predicate on the "product_name" field.
func ProductNameIn(vs ...string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldIn(FieldProductName, vs...))
}

// ProductNameNotIn applies the NotIn predicate on the "product_name" field.
func ProductNameNotIn(vs ...string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNotIn(FieldProductName, vs...))
}

// ProductNameGT applies the GT predicate on the "product_name" field.
func ProductNameGT(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGT(FieldProductName, v))
}

// ProductNameGTE applies the GTE predicate on the "product_name" field.
func ProductNameGTE(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGTE(FieldProductName, v))
}

// ProductNameLT applies the LT predicate on the "product_name" field.
func ProductNameLT(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLT(FieldProductName, v))
}

// ProductNameLTE applies the LTE predicate on the "product_name" field.
func ProductNameLTE(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLTE(FieldProductName, v))
}

// ProductNameContains applies the Contains predicate on the "product_name" field.
func ProductNameContains(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldContains(FieldProductName, v))
}

// ProductNameHasPrefix applies the HasPrefix predicate on the "product_name" field.
func ProductNameHasPrefix(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldHasPrefix(FieldProductName, v))
}

// ProductNameHasSuffix applies the HasSuffix predicate on the "product_name" field.
func ProductNameHasSuffix(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldHasSuffix(FieldProductName, v))
}

// ProductNameEqualFold applies the EqualFold predicate on the "product_name" field.
func ProductNameEqualFold(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEqualFold(FieldProductName, v))
}

// ProductNameContainsFold applies the ContainsFold predicate on the "product_name" field.
func ProductNameContainsFold(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldContainsFold(FieldProductName, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLTE(FieldPrice, v))
}

// AmountUsdEQ applies the EQ predicate on the "amount_usd" field.
func AmountUsdEQ(v float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldAmountUsd, v))
}

// AmountUsdNEQ applies the NEQ predicate on the "amount_usd" field.
func AmountUsdNEQ(v float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNEQ(FieldAmountUsd, v))
}

// AmountUsdIn applies the In predicate on the "amount_usd" field.
func AmountUsdIn(vs ...float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldIn(FieldAmountUsd, vs...))
}

// AmountUsdNotIn applies the NotIn predicate on the "amount_usd" field.
func AmountUsdNotIn(vs ...float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNotIn(FieldAmountUsd, vs...))
}

// AmountUsdGT applies the GT predicate on the "amount_usd" field.
func AmountUsdGT(v float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGT(FieldAmountUsd, v))
}

// AmountUsdGTE applies the GTE predicate on the "amount_usd" field.
func AmountUsdGTE(v float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGTE(FieldAmountUsd, v))
}

// AmountUsdLT applies the LT predicate on the "amount_usd" field.
func AmountUsdLT(v float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLT(FieldAmountUsd, v))
}

// AmountUsdLTE applies the LTE predicate on the "amount_usd" field.
func AmountUsdLTE(v float64) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLTE(FieldAmountUsd, v))
}

// ValidityDaysEQ applies the EQ predicate on the "validity_days" field.
func ValidityDaysEQ(v int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityDaysNEQ applies the NEQ predicate on the "validity_days" field.
func ValidityDaysNEQ(v int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNEQ(FieldValidityDays, v))
}

// ValidityDaysIn applies the In predicate on the "validity_days" field.
func ValidityDaysIn(vs ...int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldIn(FieldValidityDays, vs...))
}

// ValidityDaysNotIn applies the NotIn predicate on the "validity_days" field.
func ValidityDaysNotIn(vs ...int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNotIn(FieldValidityDays, vs...))
}

// ValidityDaysGT applies the GT predicate on the "validity_days" field.
func ValidityDaysGT(v int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGT(FieldValidityDays, v))
}

// ValidityDaysGTE applies the GTE predicate on the "validity_days" field.
func ValidityDaysGTE(v int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGTE(FieldValidityDays, v))
}

// ValidityDaysLT applies the LT predicate on the "validity_days" field.
func ValidityDaysLT(v int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLT(FieldValidityDays, v))
}

// ValidityDaysLTE applies the LTE predicate on the "validity_days" field.
func ValidityDaysLTE(v int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLTE(FieldValidityDays, v))
}

// FeaturesEQ applies the EQ predicate on the "features" field.
func FeaturesEQ(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldFeatures, v))
}

// FeaturesNEQ applies the NEQ predicate on the "features" field.
func FeaturesNEQ(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNEQ(FieldFeatures, v))
}

// FeaturesIn applies the In predicate on the "features" field.
func FeaturesIn(vs ...string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldIn(FieldFeatures, vs...))
}

// FeaturesNotIn applies the NotIn predicate on the "features" field.
func FeaturesNotIn(vs ...string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNotIn(FieldFeatures, vs...))
}

// FeaturesGT applies the GT predicate on the "features" field.
func FeaturesGT(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGT(FieldFeatures, v))
}

// FeaturesGTE applies the GTE predicate on the "features" field.
func FeaturesGTE(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGTE(FieldFeatures, v))
}

// FeaturesLT applies the LT predicate on the "features" field.
func FeaturesLT(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLT(FieldFeatures, v))
}

// FeaturesLTE applies the LTE predicate on the "features" field.
func FeaturesLTE(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLTE(FieldFeatures, v))
}

// FeaturesContains applies the Contains predicate on the "features" field.
func FeaturesContains(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldContains(FieldFeatures, v))
}

// FeaturesHasPrefix applies the HasPrefix predicate on the "features" field.
func FeaturesHasPrefix(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldHasPrefix(FieldFeatures, v))
}

// FeaturesHasSuffix applies the HasSuffix predicate on the "features" field.
func FeaturesHasSuffix(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldHasSuffix(FieldFeatures, v))
}

// FeaturesEqualFold applies the EqualFold predicate on the "features" field.
func FeaturesEqualFold(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEqualFold(FieldFeatures, v))
}

// FeaturesContainsFold applies the ContainsFold predicate on the "features" field.
func FeaturesContainsFold(v string) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldContainsFold(FieldFeatures, v))
}

// ForSaleEQ applies the EQ predicate on the "for_sale" field.
func ForSaleEQ(v bool) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldForSale, v))
}

// ForSaleNEQ applies the NEQ predicate on the "for_sale" field.
func ForSaleNEQ(v bool) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNEQ(FieldForSale, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUsageCards applies the HasEdge predicate on the "usage_cards" edge.
func HasUsageCards() predicate.UsageCardPlan {
	return predicate.UsageCardPlan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageCardsTable, UsageCardsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageCardsWith applies the HasEdge predicate on the "usage_cards" edge with a given conditions (other predicates).
func HasUsageCardsWith(preds ...predicate.UserUsageCard) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(func(s *sql.Selector) {
		step := newUsageCardsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRedeemCodes applies the HasEdge predicate on the "redeem_codes" edge.
func HasRedeemCodes() predicate.UsageCardPlan {
	return predicate.UsageCardPlan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RedeemCodesTable, RedeemCodesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRedeemCodesWith applies the HasEdge predicate on the "redeem_codes" edge with a given conditions (other predicates).
func HasRedeemCodesWith(preds ...predicate.RedeemCode) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(func(s *sql.Selector) {
		step := newRedeemCodesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageCardPlan) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageCardPlan) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageCardPlan) predicate.UsageCardPlan {
	return predicate.UsageCardPlan(sql.NotPredicates(p))
}
